"""
Generate an idempotent load.sql from the seed JSON files.

Run:  python import/generate_sql.py     (from fragrance-kb/)
Output: seed/load.sql

The generated file is pure SQL with ON CONFLICT upserts, so it can be applied to
PostgreSQL or Supabase with no Python/driver dependency:

    psql "$DATABASE_URL" -f schema/schema.sql
    psql "$DATABASE_URL" -f seed/load.sql

Re-running is safe (idempotent upserts keyed on the stable slug ids).
"""
from __future__ import annotations

import json
import os

SEED = "seed"
OUT = os.path.join(SEED, "load.sql")


def q(v):
    """SQL literal for a scalar."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def arr(values):
    """text[] literal."""
    if not values:
        return "'{}'"
    inner = ", ".join(q(v) for v in values)
    return f"array[{inner}]::text[]"


def load(name):
    with open(os.path.join(SEED, name), encoding="utf-8") as fh:
        return json.load(fh)


def main():
    brands = load("brands.json")
    notes = load("notes.json")
    accords = load("accords.json")
    frags = load("fragrances.json")
    rels = load("clone_relationships.json")

    lines = ["-- Auto-generated by import/generate_sql.py. Do not edit by hand.",
             "-- Idempotent: safe to re-run. Apply schema/schema.sql first.",
             "begin;",
             "set constraints all deferred;", ""]

    lines.append("-- brands")
    for b in brands:
        lines.append(
            f"insert into brand (id, name, kind, aliases) values "
            f"({q(b['id'])}, {q(b['name'])}, {q(b['kind'])}, {arr(b['aliases'])}) "
            f"on conflict (id) do update set name=excluded.name, "
            f"kind=excluded.kind, aliases=excluded.aliases;")

    lines.append("\n-- notes")
    for n in notes:
        lines.append(
            f"insert into note (id, name, aliases) values "
            f"({q(n['id'])}, {q(n['name'])}, {arr(n['aliases'])}) "
            f"on conflict (id) do update set name=excluded.name, "
            f"aliases=excluded.aliases;")

    lines.append("\n-- accords")
    for a in accords:
        lines.append(
            f"insert into accord (id, name) values ({q(a['id'])}, {q(a['name'])}) "
            f"on conflict (id) do update set name=excluded.name;")

    lines.append("\n-- fragrances")
    for f in frags:
        lines.append(
            f"insert into fragrance (id, brand_id, name, kind, dupe_status, "
            f"concentration, gender, category, approx_price_inr) values "
            f"({q(f['id'])}, {q(f['brandId'])}, {q(f['name'])}, {q(f['kind'])}, "
            f"{q(f['dupeStatus'])}, {q(f['concentration'])}, {q(f['gender'])}, "
            f"{q(f['category'])}, {q(f['approxPriceINR'])}) "
            f"on conflict (id) do update set "
            f"brand_id=excluded.brand_id, name=excluded.name, kind=excluded.kind, "
            f"dupe_status=excluded.dupe_status, concentration=excluded.concentration, "
            f"gender=excluded.gender, category=excluded.category, "
            f"approx_price_inr=excluded.approx_price_inr;")

    # note-name -> note-id and accord-name -> accord-id lookups
    note_id = {n["name"]: n["id"] for n in notes}
    accord_id = {a["name"]: a["id"] for a in accords}

    lines.append("\n-- fragrance notes / accords (clear then insert per fragrance)")
    for f in frags:
        lines.append(f"delete from fragrance_note where fragrance_id={q(f['id'])};")
        for layer in ("top", "heart", "base"):
            for n in f["notes"][layer]:
                lines.append(
                    f"insert into fragrance_note (fragrance_id, note_id, layer) "
                    f"values ({q(f['id'])}, {q(note_id[n])}, {q(layer)}) "
                    f"on conflict do nothing;")
        lines.append(f"delete from fragrance_accord where fragrance_id={q(f['id'])};")
        for a in f["accords"]:
            lines.append(
                f"insert into fragrance_accord (fragrance_id, accord_id) "
                f"values ({q(f['id'])}, {q(accord_id[a])}) on conflict do nothing;")

    # sources: collect from claims
    lines.append("\n-- sources")
    sources = {}
    for r in rels:
        for c in r["claims"]:
            sources.setdefault(c["sourceId"], {
                "id": c["sourceId"], "name": c["sourceName"],
                "trust": c["trustWeight"], "url": c["url"]})
    for s in sorted(sources.values(), key=lambda x: x["id"]):
        lines.append(
            f"insert into source (id, name, type, trust_weight, url) values "
            f"({q(s['id'])}, {q(s['name'])}, null, {q(s['trust'])}, {q(s['url'])}) "
            f"on conflict (id) do update set name=excluded.name, "
            f"trust_weight=excluded.trust_weight;")

    lines.append("\n-- clone relationships")
    for r in rels:
        m = r["match"]
        p = r["performance"]
        pr = r["price"]
        lines.append(
            f"insert into clone_relationship (id, original_fragrance_id, "
            f"clone_fragrance_id, category, confidence_tier, match_opening, "
            f"match_heart, match_drydown, match_overall, longevity_comparison, "
            f"projection_comparison, sillage_comparison, original_approx_inr, "
            f"clone_approx_inr, confidence, why_it_matches, differences, verified) "
            f"values ({q(r['id'])}, {q(r['originalFragranceId'])}, "
            f"{q(r['cloneFragranceId'])}, {q(r['category'])}, {q(r['confidenceTier'])}, "
            f"{q(m['opening'])}, {q(m['heart'])}, {q(m['drydown'])}, {q(m['overall'])}, "
            f"{q(p['longevityComparison'])}, {q(p['projectionComparison'])}, "
            f"{q(p['sillageComparison'])}, {q(pr['originalApproxINR'])}, "
            f"{q(pr['cloneApproxINR'])}, {q(r['confidence'])}, "
            f"{arr(r['whyItMatches'])}, {arr(r['differences'])}, {q(r['verified'])}) "
            f"on conflict (id) do update set "
            f"category=excluded.category, confidence_tier=excluded.confidence_tier, "
            f"match_overall=excluded.match_overall, "
            f"confidence=excluded.confidence, verified=excluded.verified;")

    lines.append("\n-- clone claims (provenance)")
    for r in rels:
        for c in r["claims"]:
            lines.append(
                f"insert into clone_claim (relationship_id, source_id, url, "
                f"confidence, reported_similarity, note, trust_weight) values "
                f"({q(r['id'])}, {q(c['sourceId'])}, {q(c['url'])}, "
                f"{q(c['confidence'])}, {q(c['reportedSimilarity'])}, "
                f"{q(c['note'])}, {q(c['trustWeight'])}) "
                f"on conflict (relationship_id, source_id, url) do update set "
                f"confidence=excluded.confidence, "
                f"reported_similarity=excluded.reported_similarity;")

    lines.append("\ncommit;")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT} ({len(lines)} statements-ish)")


if __name__ == "__main__":
    main()
