#!/usr/bin/env python3
"""
Noir Vault Fragrance KB — Batch 4 builder.
Adds Arabiyat Prestige #31-58 (28) + French Avenue cluster 1 (18) to the same DB.
Prior batches are pulled from their modules unchanged.
"""
import json
import build_batch3 as b3
b2 = b3.b2
b1 = b3.b1

# ===========================================================================
# ARABIYAT PRESTIGE  #31-58
# ===========================================================================
ARAB4 = [
 dict(name="Nashwa", g="unisex", c="EDP", y=2023, fam="Aromatic Citrus",
      style="grapefruit citrus woody", lon="moderate", proj="moderate",
      prof="Grapefruit/bergamot over ginger-patchouli with a vetiver-musk-amber base — a realistic-citrus twist on the Bvlgari Tygar DNA.",
      acc=["citrus","aromatic","woody","fresh","mineral"],
      top=["grapefruit","bergamot"], heart=["ginger","patchouli"], base=["vetiver","musk","amber"]),
 dict(name="Nashwa Noir", g="unisex", c="EDP", y=2023, fam="Leather Oud",
      style="spicy leather oud", lon="long", proj="strong",
      prof="Bergamot/cinnamon/nutmeg/bark over nagarmotha-geranium with a black-musk-leather-oud-patchouli-saffron base; dark spicy leather-oud, no confirmed designer target.",
      acc=["leather","oud","warm spicy","woody","smoky"],
      top=["bergamot","cinnamon","nutmeg","bark"], heart=["nagarmotha","geranium"],
      base=["black musk","leather","oud","patchouli","saffron"], nr=1),
 dict(name="Nashwa Oud", g="unisex", c="EDP", y=2024, fam="Woody Oud",
      style="saffron incense oud", lon="long", proj="strong",
      prof="Geranium/saffron/bergamot over olibanum-ambroxan-cedar with an oud-patchouli-vanilla base; incense-oud woody, no confirmed target.",
      acc=["oud","woody","incense","warm spicy","amber"],
      top=["geranium","saffron","bergamot"], heart=["olibanum","ambroxan","cedar"],
      base=["oud","patchouli","vanilla"], nr=1),
 dict(name="Nashwa Smoke", g="unisex", c="EDP", y=2024, fam="Smoky Oud",
      style="smoky leather caramel oud", lon="long", proj="strong",
      prof="Bergamot/mandarin over olibanum-cedar with an oud-leather-caramel-amber base — a Bvlgari Le Gemme Onekh-style smoky oud.",
      acc=["smoky","oud","leather","sweet","incense"],
      top=["bergamot","mandarin"], heart=["olibanum","cedar"],
      base=["oud","patchouli","leather","caramel","amber"]),
 dict(name="Nayel Her Majesty", g="women", c="EDP", y=2024, fam="Amber Gourmand",
      style="pear coffee gourmand", lon="long", proj="moderate",
      prof="Pear/cinnamon/mandarin over orange blossom with a vanilla-patchouli-coffee base; rich gourmand floral, no confirmed target.",
      acc=["sweet","gourmand","fruity","coffee","vanilla"],
      top=["pear","cinnamon","mandarin"], heart=["orange blossom"], base=["vanilla","patchouli","coffee"], nr=1),
 dict(name="Nayel King", g="men", c="EDP", y=2023, fam="Woody Spicy",
      style="woody spicy", lon="long", proj="strong",
      prof="Nayel-line masculine woody-spicy; detailed pyramid not documented in reviewed sources.",
      acc=["woody","warm spicy","amber","aromatic"], nr=1),
 dict(name="Nayel Oud", g="unisex", c="EDP", y=2023, fam="Aromatic Oud",
      style="powdery woody oud", lon="long", proj="strong",
      prof="Violet leaf/bergamot over cedar-lily-rose with a patchouli-oud-amber-vanilla base — reviewers call it ~98% YSL Tuxedo.",
      acc=["oud","woody","powdery","aromatic","floral"],
      top=["violet leaf","bergamot"], heart=["cedar","lily-of-the-valley","rose"],
      base=["patchouli","oud","amber","vanilla"]),
 dict(name="Nayel Queen", g="unisex", c="EDP", y=2023, fam="Tobacco Woody",
      style="tobacco suede", lon="long", proj="strong",
      prof="Tobacco/black pepper/pink pepper over cedar-saffron with a vanilla-suede-benzoin-tonka base; tobacco-suede, no confirmed target.",
      acc=["tobacco","warm spicy","suede","sweet","woody"],
      top=["tobacco","black pepper","pink pepper"], heart=["cedar","saffron"],
      base=["vanilla","suede","benzoin","tonka bean"], nr=1),
 dict(name="Nyla", g="women", c="EDP", y=2024, fam="Floral Tropical",
      style="coconut tropical floral", lon="moderate", proj="moderate",
      prof="Coconut/peach/mandarin over tiare-white flowers-jasmine-rose with a white-musk-patchouli base; tropical floral, no confirmed target.",
      acc=["floral","coconut","fruity","tropical","musky"],
      top=["coconut","peach","mandarin","bergamot"], heart=["tiare","white flowers","jasmine","rose"],
      base=["white musk","patchouli"], nr=1),
 dict(name="Nyla Sherbet", g="women", c="EDP", y=2025, fam="Fruity",
      style="berry sherbet", lon="moderate", proj="moderate",
      prof="Strawberry/mandarin over plum with a musk-sandalwood base; bright fruity, no confirmed target.",
      acc=["fruity","sweet","fresh","musky"],
      top=["strawberry","mandarin"], heart=["plum"], base=["musk","sandalwood"], nr=1),
 dict(name="Nyla Suede", g="unisex", c="EDP", y=2024, fam="Leather Gourmand",
      style="sweet leathery gourmand", lon="long", proj="strong",
      prof="Coconut/caramel/praline over vanilla-cashmere-milk-ylang with a leather-sandalwood-musk-ambergris base; sweet leathery gourmand.",
      acc=["sweet","leather","gourmand","coconut","creamy"],
      top=["coconut","caramel","praline"], heart=["vanilla","cashmere wood","milk","ylang-ylang"],
      base=["leather","sandalwood","musk","ambergris"], nr=1),
 dict(name="Nyla Vani-Elle", g="unisex", c="EDP", y=2024, fam="Amber Vanilla",
      style="vanilla caramel", lon="long", proj="moderate",
      prof="Vanilla bean/jasmine over caramel-amber with a vanilla-tonka-musk base; cozy vanilla gourmand.",
      acc=["sweet","vanilla","gourmand","amber","creamy"],
      top=["vanilla bean","jasmine"], heart=["caramel","amber"], base=["vanilla","tonka bean","musk"], nr=1),
 dict(name="Portrait", g="unisex", c="EDP", y=2024, fam="Woody",
      style="woody", lon="long", proj="moderate",
      prof="Arabiyat 'Portrait' base (distinct from Afnan Portrait Abstract); detailed pyramid not documented.",
      acc=["woody","amber","aromatic","sweet"], nr=1),
 dict(name="Portrait Azure", g="men", c="EDP", y=2025, fam="Amber Spicy",
      style="fresh spicy gourmand", lon="long", proj="strong",
      prof="Reviewed as a fresher, less-sweet take on Dior Sauvage Elixir. NOTE: Fragrantica's listed pyramid (red fruits/hazelnut/lychee/cypriol/rose/vanilla) reads more gourmand than Sauvage Elixir — a data discrepancy flagged for review.",
      acc=["warm spicy","fresh","amber","sweet","woody"],
      top=["red fruits","hazelnut","lychee"], heart=["cypriol","rose","magnolia"],
      base=["vanilla","gourmand accord","ambergris"], nr=1),
 dict(name="Portrait Café Noir", g="unisex", c="EDP", y=2025, fam="Woody Chypre",
      style="fruity coffee woody", lon="long", proj="strong",
      prof="Bergamot/blackcurrant over akigalawood-patchouli-caramel with an evernyl-amber-musk base — marketed as an Aventus x Baccarat Rouge 540 blend.",
      acc=["fruity","woody","sweet","chypre","amber"],
      top=["bergamot","black currant"], heart=["akigalawood","patchouli","caramel"],
      base=["evernyl","amber","musk"]),
 dict(name="Raees", g="men", c="EDP", y=2024, fam="Fruity",
      style="fruity", lon="long", proj="strong",
      prof="Base Raees fruity; detailed pyramid not documented.",
      acc=["fruity","sweet","amber","fresh"], nr=1),
 dict(name="Raees Aurum", g="unisex", c="EDP", y=2025, fam="Fruity",
      style="juicy fruity", lon="long", proj="strong",
      prof="Juicy-fruity reviewers place near the Xerjoff Erba (Pura/'Gold') family; target not firmly pinned.",
      acc=["fruity","sweet","citrus","amber"], nr=1),
 dict(name="Raees Luxury Edition", g="men", c="EDP", y=2025, fam="Woody Aquatic",
      style="fresh woody aquatic", lon="long", proj="strong",
      prof="Woody-aquatic; no confirmed designer target.",
      acc=["aquatic","woody","fresh","aromatic"], nr=1),
 dict(name="Raees Twilight Aura", g="unisex", c="EDP", y=2025, fam="Fruity",
      style="natural fruity", lon="long", proj="strong",
      prof="Tropical/green fruity-citrus over floral-woody-amber — a more natural, wearable Xerjoff Erba Pura take.",
      acc=["fruity","sweet","citrus","amber","green"],
      top=["tropical fruits","fruity notes","green notes","citrus"], heart=["floral notes","woody notes","amber"],
      base=["amber","musk","sweet notes"]),
 dict(name="Ramad", g="unisex", c="EDP", y=2025, fam="Woody Smoky",
      style="ashy woody", lon="long", proj="strong",
      prof="Base Ramad ('ash') smoky-woody; detailed pyramid not documented.",
      acc=["woody","smoky","incense","amber"], nr=1),
 dict(name="Ramad Earthy", g="unisex", c="EDP", y=2025, fam="Woody Earthy",
      style="earthy woody", lon="long", proj="strong",
      prof="Earthy-woody Ramad flanker with cult following; detailed pyramid not documented.",
      acc=["woody","earthy","smoky","amber"], nr=1),
 dict(name="Ramad Louban", g="unisex", c="EDP", y=2025, fam="Woody Spicy",
      style="resinous spicy woody", lon="long", proj="strong",
      prof="Pepper/myrrh/cardamom/hazelnut/cinnamon over davana-labdanum-pine-cypriol with a cedar-amber-benzoin-vetiver-oakmoss base; warm smoky resinous woody.",
      acc=["woody","warm spicy","incense","smoky","amber"],
      top=["pepper","myrrh","cardamom","hazelnut","cinnamon"], heart=["davana","labdanum","pine","cypriol"],
      base=["cedar","amber","benzoin","vetiver","oakmoss"], nr=1),
 dict(name="Ramad Myrrh", g="unisex", c="EDP", y=2025, fam="Resinous Woody",
      style="myrrh resinous", lon="long", proj="strong",
      prof="Myrrh-forward resinous Ramad flanker; detailed pyramid not documented.",
      acc=["incense","woody","resinous","warm spicy","amber"], nr=1),
 dict(name="Ramad Oriental", g="unisex", c="EDP", y=2025, fam="Amber Woody",
      style="oriental woody", lon="long", proj="strong",
      prof="Oriental-woody Ramad flanker with cult following; detailed pyramid not documented.",
      acc=["amber","woody","warm spicy","sweet"], nr=1),
 dict(name="Safa", g="women", c="EDP", y=2025, fam="Floral Fruity Gourmand",
      style="lychee rose gourmand", lon="long", proj="strong",
      prof="Lychee/hazelnut/red fruits over rose-magnolia-cypriol with a vanilla-gourmand-ambergris base — a Delina Exclusif-leaning fruity-floral gourmand.",
      acc=["floral","fruity","rose","sweet","gourmand"],
      top=["lychee","hazelnut","red fruits"], heart=["rose","magnolia","cypriol"],
      base=["vanilla","gourmand accord","ambergris"]),
 dict(name="Swar Seduire", g="unisex", c="EDP", y=2025, fam="Amber Woody",
      style="date leather oud", lon="long", proj="strong",
      prof="Dates/cinnamon/marigold over leather-sugarcane-amber with a vanilla-patchouli-oud base; sweet oriental woody, no confirmed designer target.",
      acc=["sweet","amber","leather","oud","warm spicy"],
      top=["dates","cinnamon","marigold"], heart=["leather","sugar cane","amber"],
      base=["vanilla","patchouli","oud"], nr=1),
 dict(name="Swar Venin", g="unisex", c="EDP", y=2025, fam="Amber Woody",
      style="oriental woody", lon="long", proj="strong",
      prof="Swar-line 'venin' oriental woody; detailed pyramid not documented.",
      acc=["amber","woody","warm spicy","sweet"], nr=1),
 dict(name="Uhud", g="unisex", c="EDP", y=2025, fam="Amber Gourmand",
      style="caramel honey vanilla gourmand", lon="long", proj="strong",
      prof="Caramel/red fruits/rose over raspberry-honey-tonka with a vanilla-white-musk-amber base; warm honeyed gourmand, no confirmed target.",
      acc=["sweet","gourmand","vanilla","fruity","amber"],
      top=["caramel","red fruits","rose"], heart=["raspberry","honey","tonka bean"],
      base=["vanilla","white musk","amber"], nr=1),
]

# ===========================================================================
# FRENCH AVENUE  cluster 1 (18)
# ===========================================================================
FA4 = [
 dict(name="Royal Blend", g="unisex", c="EDP", y=2023, fam="Amber Gourmand",
      style="boozy praline gourmand", lon="long", proj="moderate",
      prof="Boozy cognac accord with cinnamon and oak over praline and tonka — the go-to ~85% Kilian Angels' Share clone.",
      acc=["boozy","sweet","gourmand","warm spicy","vanilla"],
      top=["cognac","cinnamon"], heart=["praline","tonka bean","oak"], base=["vanilla","sandalwood"]),
 dict(name="Royal Blend Nero", g="unisex", c="EDP", y=2024, fam="Amber Gourmand",
      style="fresher boozy gourmand", lon="long", proj="moderate",
      prof="A fresher, dry-wood-and-cinnamon flanker of Royal Blend / Angels' Share.",
      acc=["boozy","sweet","warm spicy","vanilla","woody"],
      top=["cinnamon"], heart=["dry wood","tonka bean"], base=["vanilla"], nr=1),
 dict(name="Royal Blend Bourbon", g="unisex", c="EDP", y=2025, fam="Aromatic",
      style="boozy aromatic", lon="long", proj="moderate",
      prof="Cinnamon/peppermint/bark/basil over bourbon whiskey and lavender with an oak-Peru balsam base; boozy aromatic, no confirmed designer target.",
      acc=["boozy","aromatic","warm spicy","woody"],
      top=["cinnamon","peppermint","bark","basil"], heart=["bourbon whiskey","lavender"],
      base=["oak","peru balsam"], nr=1),
 dict(name="Royal Blend Vintage", g="unisex", c="EDP", y=2025, fam="Oriental Fougere",
      style="boozy fougere", lon="long", proj="moderate",
      prof="Reviewed as a clone of 'Old Fashioned' (some liken it to Single Malt) — a boozy oriental fougere. Target house unconfirmed.",
      acc=["boozy","aromatic","sweet","woody","warm spicy"], nr=1),
 dict(name="Royal Blend Sequoia", g="unisex", c="EDP", y=2025, fam="Fruity Gourmand",
      style="raspberry liquor gourmand", lon="long", proj="strong",
      prof="Strong raspberry/liquor lead reviewed as inspired by Angels' Share Paradis' middle notes.",
      acc=["fruity","boozy","sweet","gourmand","amber"],
      top=["raspberry","liquor accord"], heart=["praline"], base=["vanilla","tonka bean"], nr=1),
 dict(name="Liquid Brun", g="men", c="EDP", y=2024, fam="Amber Gourmand",
      style="almond praline gourmand", lon="long", proj="strong",
      prof="Reviewed as a near-1:1 Parfums de Marly Althair clone — almond/praline/vanilla-ambroxan gourmand.",
      acc=["sweet","gourmand","almond","vanilla","warm spicy"],
      top=["bergamot","cinnamon"], heart=["vanilla","almond"], base=["tonka bean","praline","ambroxan"]),
 dict(name="Liquid Brun Limited Edition", g="men", c="EDP", y=2025, fam="Amber Gourmand",
      style="richer almond gourmand", lon="long", proj="strong",
      prof="A richer limited-edition flanker of Liquid Brun (Althair lane); detailed pyramid not documented.",
      acc=["sweet","gourmand","almond","vanilla","amber"], nr=1),
 dict(name="Aether", g="unisex", c="Extrait", y=2024, fam="Aromatic Fruity",
      style="green apple aromatic", lon="long", proj="strong",
      prof="Green apple/bergamot/mandarin over cedar-petitgrain-cashmeran-violet with a musk-oakmoss-amberwood base — a Parfums de Marly Greenly dupe.",
      acc=["green","fruity","aromatic","fresh","woody"],
      top=["green apple","bergamot","mandarin"], heart=["cedar","petitgrain","cashmeran","violet"],
      base=["musk","oakmoss","amberwood"]),
 dict(name="Atlantis Extrait", g="unisex", c="Extrait", y=2025, fam="Fruity Aquatic",
      style="coconut watermelon aquatic", lon="long", proj="strong",
      prof="Orange/mandarin/lemon over watermelon-coconut with an ambergris-cacao-amberwood base — a Wavechild-leaning fruity aquatic.",
      acc=["fruity","aquatic","sweet","coconut","marine"],
      top=["orange","mandarin","lemon"], heart=["watermelon","coconut"], base=["ambergris","cacao","amberwood"], nr=1),
 dict(name="Spectre Ghost", g="men", c="EDP", y=2023, fam="Amber Gourmand",
      style="spicy sweet woody", lon="long", proj="strong",
      prof="Ginger/cardamom/bergamot over pink pepper-blackcurrant-rose with a vanilla-cedar-patchouli base — a well-known Nishane Ani clone.",
      acc=["sweet","warm spicy","vanilla","woody","fruity"],
      top=["ginger","cardamom","bergamot"], heart=["pink pepper","black currant","rose"],
      base=["vanilla","cedar","patchouli"]),
 dict(name="Spectre Wraith", g="men", c="EDP", y=2024, fam="Amber Vanilla",
      style="boozy coffee vanilla", lon="long", proj="strong",
      prof="Rum/spices over coffee-sandalwood-patchouli-vetiver with a sugarcane base — inspired by Kilian Black Phantom.",
      acc=["boozy","sweet","coffee","amber","vanilla"],
      top=["rum","spices"], heart=["coffee","sandalwood","patchouli","vetiver"], base=["sugar cane"]),
 dict(name="Spectre Pinnace", g="unisex", c="EDP", y=2024, fam="Citrus Aromatic",
      style="citrus aquatic", lon="moderate", proj="moderate",
      prof="NAME AMBIGUITY: no single 'Spectre Pinnace' release found — the list appears to conflate French Avenue 'Spectre' (smoky leather) and 'Pinnace' (a bitter-lemon Louis Vuitton Pacific Chill clone). Recorded here as the Pinnace / Pacific Chill reading pending confirmation.",
      acc=["citrus","fresh","fruity","aromatic","aquatic"],
      top=["lemon","bergamot"], heart=["apricot"], base=["musk","amberwood"], nr=1),
 dict(name="Pinnace Noir", g="unisex", c="EDP", y=2024, fam="Fruity Aromatic",
      style="apple spicy woody", lon="long", proj="moderate",
      prof="Apple/orange blossom/lemon/bergamot over cinnamon-geranium-clove-rosewood with a vanilla-sandalwood-cedar base — a wearable Hugo Boss Bottled take.",
      acc=["fruity","aromatic","warm spicy","woody","sweet"],
      top=["apple","orange blossom","lemon","bergamot"], heart=["cinnamon","geranium","clove","brazilian rosewood"],
      base=["vanilla","sandalwood","cedar"]),
 dict(name="Pinnace Oryn", g="men", c="EDP", y=2025, fam="Citrus",
      style="fresh citrus ginger", lon="moderate", proj="moderate",
      prof="Mandarin/orange/bergamot over ginger with an ambergris base — an affordable Louis Vuitton Afternoon Swim alternative.",
      acc=["citrus","fresh","aromatic","musky"],
      top=["mandarin","orange","bergamot"], heart=["ginger"], base=["ambergris"]),
 dict(name="Azzure Oud", g="men", c="EDP", y=2024, fam="Fruity Oud",
      style="passionfruit oud", lon="long", proj="strong",
      prof="Passionfruit/rose/saffron over oud-benzoin-patchouli with a leather-guaiac-amber-cedar-sandalwood-labdanum base — a ~96% Maison Crivelli Oud Maracuja clone.",
      acc=["oud","fruity","woody","leather","amber"],
      top=["passion fruit","fruity notes","rose","saffron"], heart=["oud","benzoin","patchouli"],
      base=["leather","guaiac wood","amber","cedar","sandalwood","labdanum"]),
 dict(name="Cocoa Morado", g="unisex", c="EDP", y=2024, fam="Amber Oud Gourmand",
      style="spicy date oud", lon="long", proj="strong",
      prof="Cinnamon/saffron/cardamom over sweet dates-caramel-oud-incense — a Maison Crivelli Oud Cadenza clone.",
      acc=["oud","sweet","warm spicy","gourmand","incense"],
      top=["cinnamon","saffron","cardamom"], heart=["dates","caramel","oud","incense"], base=["amber","woods"]),
 dict(name="Éclair Affair", g="unisex", c="EDP", y=2025, fam="Gourmand",
      style="creamy sweet gourmand", lon="long", proj="strong",
      prof="Creamy sweet gourmand with a warm base; no confirmed designer target.",
      acc=["sweet","gourmand","vanilla","creamy"], nr=1),
 dict(name="Meringue Luscious", g="women", c="EDP", y=2024, fam="Gourmand",
      style="pistachio gourmand", lon="long", proj="moderate",
      prof="NAME AMBIGUITY: appears to conflate two French Avenue releases — 'Meringue' (a Crème de Cuir-leaning woody-floral-musk) and 'Luscious' (a pistachio-cardamom gourmand compared to Lattafa Éclaire Pistache). Recorded on the Luscious/pistachio reading pending confirmation.",
      acc=["sweet","gourmand","pistachio","nutty","vanilla"],
      top=["pistachio","cardamom","bergamot"], heart=["peanut","saffron"], base=["vanilla","tonka bean","honey","musk"], nr=1),
]

# ===========================================================================
# NEW REFERENCE TARGETS for Batch 4
# ===========================================================================
REFS4 = [
 dict(brand="Bvlgari", name="Le Gemme Onekh", fam="Smoky Oud",
      acc=["smoky","oud","leather","incense","amber"],
      top=["bergamot"], heart=["olibanum","cedar"], base=["oud","leather","amber"]),
 dict(brand="Maison Francis Kurkdjian", name="Baccarat Rouge 540", fam="Amber Woody Floral",
      acc=["sweet","amber","woody","saffron","floral"],
      top=["saffron","jasmine"], heart=["amberwood","ambergris"], base=["fir resin","cedar"]),
 dict(brand="Parfums de Marly", name="Greenly", fam="Aromatic Fruity",
      acc=["green","fruity","aromatic","fresh","woody"],
      top=["green apple","mint","bergamot"], heart=["violet leaf","cardamom"], base=["cedar","musk","amberwood"]),
 dict(brand="Kilian", name="Black Phantom", fam="Amber Gourmand",
      acc=["boozy","coffee","sweet","gourmand","amber"],
      top=["rum","caramel"], heart=["coffee"], base=["sugar cane","dark chocolate","sandalwood"]),
 dict(brand="Hugo Boss", name="Bottled", fam="Fruity Aromatic",
      acc=["fruity","aromatic","warm spicy","woody","fresh"],
      top=["apple","bergamot","lemon"], heart=["cinnamon","clove","geranium"], base=["sandalwood","cedar","vanilla"]),
 dict(brand="Louis Vuitton", name="Afternoon Swim", fam="Citrus",
      acc=["citrus","fresh","aromatic","sweet"],
      top=["orange","mandarin","bergamot"], heart=["ginger"], base=["ambroxan","neroli"]),
 dict(brand="Maison Crivelli", name="Oud Maracuja", fam="Fruity Oud",
      acc=["oud","fruity","woody","leather","amber"],
      top=["passion fruit","saffron","rose"], heart=["oud","benzoin"], base=["leather","guaiac wood","labdanum"]),
 dict(brand="Maison Crivelli", name="Oud Cadenza", fam="Amber Oud Gourmand",
      acc=["oud","sweet","warm spicy","gourmand","incense"],
      top=["cinnamon","saffron","cardamom"], heart=["dates","caramel","oud"], base=["incense","amber","woods"]),
]

# ===========================================================================
# BATCH-4 RELATIONSHIPS
# ===========================================================================
R4 = []
def rel(frm,to,typ,ov,op,he,dr,pe,cc,reason,honest,evid,ver,nr,srcs):
    R4.append(dict(frm=frm,to=to,typ=typ,ov=ov,op=op,he=he,dr=dr,pe=pe,cc=cc,
        reason=reason,honest=honest,evid=evid,ver=ver,nr=nr,srcs=srcs,batch=4))
AP="https://www.fragrantica.com/perfume/Arabiyat-Prestige/"
FA="https://www.fragrantica.com/perfume/French-Avenue/"

# ---- Arabiyat pt.2 ----
rel("Arabiyat Prestige|Nashwa","Bvlgari|Tygar","SIMILAR_DNA",
    0.62,0.72,0.58,0.52,0.60,0.50,
    "A grapefruit-forward twist on the Bvlgari Tygar citrus DNA — reviewers note the grapefruit reads more realistic than many Tygar alternatives.",
    "Simpler and more citrus-linear than Tygar; shares DNA rather than cloning it.",
    "Fragrantica reviews describing it as a Tygar-DNA twist.",
    0,0,[AP+"Nashwa-103391.html"])
rel("Arabiyat Prestige|Nashwa Smoke","Bvlgari|Le Gemme Onekh","INSPIRED_BY",
    0.68,0.66,0.68,0.70,0.72,0.55,
    "Marketed and reviewed as a Bvlgari Le Gemme Onekh-style smoky oud — olibanum/cedar over oud, leather and caramel.",
    "A sweeter caramel facet vs the drier original; retailer-led sourcing.",
    "Fragrantica + retailer (Aromatick) listing it as an Onekh clone.",
    0,1,[FA.replace('French-Avenue','Arabiyat')+"Nashwa-Smoke-103394.html","https://aromatick.com/products/arabiyat-nashwa-smoke-edp-onekh-clone-mens-cologne"])
rel("Arabiyat Prestige|Nayel Oud","Yves Saint Laurent|Tuxedo","INSPIRED_BY",
    0.80,0.80,0.80,0.80,0.75,0.60,
    "Reviewers call it ~98% YSL Tuxedo — violet-leaf/bergamot over cedar-rose with a patchouli-oud-amber-vanilla base.",
    "Single strong review; slightly more oud in the base than Tuxedo.",
    "Fragrantica reviews naming Tuxedo at ~98%.",
    0,1,[AP+"Nayel-Oud-103379.html"])
rel("Arabiyat Prestige|Portrait Azure","Dior|Sauvage Elixir","INSPIRED_BY",
    0.60,0.62,0.58,0.58,0.72,0.45,
    "Reviewed as a fresher, less-sweet take on Dior Sauvage Elixir.",
    "Fragrantica's published pyramid (red fruits/lychee/gourmand) doesn't match Sauvage Elixir's spicy profile — a source discrepancy; treat with caution.",
    "Fragrantica user reviews ('clone of Sauvage Elixir, fresher/unsweetened').",
    0,1,[AP+"Portrait-Azure-115534.html"])
rel("Arabiyat Prestige|Portrait Café Noir","Creed|Aventus","HYBRID_DNA",
    0.52,0.58,0.50,0.48,0.70,0.45,
    "Marketed as a blend of Creed Aventus and Baccarat Rouge 540 — fruity blackcurrant/bergamot with a sweet ambery base.",
    "Neither parent is cloned outright; it fuses Aventus fruitiness with BR540 sweetness.",
    "Fragrantica + retailer descriptions naming the Aventus x BR540 blend.",
    0,1,[AP+"Portrait-Cafe-Noir-115536.html"])
rel("Arabiyat Prestige|Portrait Café Noir","Maison Francis Kurkdjian|Baccarat Rouge 540","HYBRID_DNA",
    0.50,0.45,0.52,0.54,0.70,0.45,
    "Second parent: the sweet amberwood-saffron facet leans Baccarat Rouge 540.",
    "Only the sweet ambery drydown converges with BR540.",
    "Same Aventus x BR540 marketing/review sourcing.",
    0,1,[AP+"Portrait-Cafe-Noir-115536.html"])
rel("Arabiyat Prestige|Raees Twilight Aura","Xerjoff|Erba Pura","INSPIRED_BY",
    0.70,0.72,0.68,0.66,0.70,0.55,
    "A more natural, wearable Xerjoff Erba Pura take — tropical/green fruity-citrus over amber-musk.",
    "Tones down Erba Pura's super-strong candied fruit; reads more natural.",
    "Fragrantica + Parfumo reviews naming Erba Pura.",
    0,0,[AP+"Raees-Twilight-Aura-115542.html","https://www.parfumo.com/Perfumes/arabiyat-prestige/raees-twilight-aura"])
rel("Arabiyat Prestige|Raees Aurum","Xerjoff|Erba Pura","SIMILAR_DNA",
    0.55,0.58,0.54,0.50,0.68,0.40,
    "Juicy-fruity placed near the Xerjoff Erba (Pura/'Gold') family by reviewers.",
    "Target not firmly pinned ('Erba Gold' is not a confirmed release); low confidence.",
    "Fragrantica reviews.",
    0,1,[AP+"Raees-Aurum-103370.html"])
rel("Arabiyat Prestige|Safa","Parfums de Marly|Delina","INSPIRED_BY",
    0.62,0.60,0.64,0.64,0.65,0.48,
    "Described as carrying Delina Exclusif DNA — lychee/red-fruits and rose into a vanilla-gourmand-ambergris base.",
    "Framed as 'inspired by, not a dupe'; hazelnut/gourmand facet differs from Delina.",
    "Fragrantica reviews naming Delina Exclusif.",
    0,1,[AP+"Safa-115550.html"])

# Arabiyat pt.2 ORIGINAL_DNA / no confirmed target
for nm,reason in {
 "Nashwa Noir":"Dark spicy leather-oud; no confirmed designer target.",
 "Nashwa Oud":"Incense-oud woody; no confirmed designer target.",
 "Nayel Her Majesty":"Pear-coffee gourmand floral; no confirmed target.",
 "Nayel King":"Masculine woody-spicy; pyramid/inspiration undocumented.",
 "Nayel Queen":"Tobacco-suede; no confirmed designer target.",
 "Nyla":"Coconut tropical floral; no confirmed target.",
 "Nyla Sherbet":"Berry-sherbet fruity; no confirmed target.",
 "Nyla Suede":"Sweet leathery gourmand; no confirmed target.",
 "Nyla Vani-Elle":"Vanilla-caramel gourmand; no confirmed target.",
 "Portrait":"Base Portrait woody; pyramid/inspiration undocumented.",
 "Raees":"Base Raees fruity; pyramid/inspiration undocumented.",
 "Raees Luxury Edition":"Woody-aquatic; no confirmed target.",
 "Ramad":"Base Ramad smoky-woody; pyramid undocumented.",
 "Ramad Earthy":"Earthy-woody flanker; pyramid undocumented.",
 "Ramad Louban":"Resinous smoky woody; no confirmed designer target.",
 "Ramad Myrrh":"Myrrh resinous flanker; pyramid undocumented.",
 "Ramad Oriental":"Oriental-woody flanker; pyramid undocumented.",
 "Swar Seduire":"Sweet date-leather-oud oriental; no confirmed target.",
 "Swar Venin":"Oriental woody flanker; pyramid undocumented.",
 "Uhud":"Caramel-honey-vanilla gourmand; no confirmed target.",
}.items():
    rel(f"Arabiyat Prestige|{nm}", f"Arabiyat Prestige|{nm}", "ORIGINAL_DNA",
        None,None,None,None,None,0.30,
        f"No cross-validated designer/niche inspiration: {reason} Stored as original DNA with closest profile exposed.",
        "Inspiration unverified — flagged for a later deepening pass.",
        "Fragrantica/Parfumo/retailer profiles for scent DNA; no confirmed clone target.",
        0,1,[AP])

# ---- French Avenue cluster 1 ----
rel("French Avenue|Royal Blend","Kilian|Angels' Share","VERIFIED_CLONE",
    0.82,0.82,0.82,0.84,0.70,0.80,
    "Widely regarded as the closest, most accurate Angels' Share clone (~85%) — boozy cognac/cinnamon/oak over praline and tonka.",
    "A slightly synthetic boozy edge the original avoids; ~6-7h vs the Kilian's longer wear.",
    "Scentonym (85% match) + Parfumo + YouTube all label it an Angels' Share clone.",
    1,0,[FA+"Royal-Blend-94022.html","https://www.scentonym.com/fragrance/french-avenue-royal-blend","https://www.parfumo.com/Perfumes/french-avenue/royal-blend"])
rel("French Avenue|Royal Blend Nero","French Avenue|Royal Blend","SIMILAR_DNA",
    0.72,0.70,0.72,0.74,0.75,0.55,
    "A fresher dry-wood-and-cinnamon flanker of Royal Blend, in the same Angels' Share gourmand lane.",
    "Fresher and less boozy than the original Royal Blend.",
    "Fragrantica line reviews.",
    0,1,[FA+"Royal-Blend-Nero-99800.html"])
rel("French Avenue|Royal Blend Sequoia","Kilian|Angels' Share","INSPIRED_BY",
    0.55,0.52,0.58,0.55,0.75,0.42,
    "Reviewed as inspired by Angels' Share Paradis' middle notes, led by a strong raspberry/liquor accord.",
    "The raspberry lead pulls it toward a fruity gourmand rather than a straight Angels' Share clone.",
    "Fragrantica reviews referencing Angels' Share Paradis.",
    0,1,[FA+"Royal-Blend-Sequoia-109710.html"])
rel("French Avenue|Liquid Brun","Parfums de Marly|Althair","INSPIRED_BY",
    0.80,0.80,0.80,0.82,0.80,0.62,
    "Reviewed as a near-1:1 Parfums de Marly Althair clone — almond/praline/vanilla-ambroxan gourmand.",
    "Single detailed source so far; held below VERIFIED_CLONE pending a second.",
    "Scentonym-style review calling it a very accurate Althair clone.",
    0,1,[FA+"Liquid-Brun-94713.html"])
rel("French Avenue|Liquid Brun Limited Edition","French Avenue|Liquid Brun","SIMILAR_DNA",
    0.75,0.75,0.75,0.75,0.80,0.50,
    "A richer limited-edition flanker of Liquid Brun in the Althair gourmand lane.",
    "Detailed pyramid not documented; treated as a stronger Liquid Brun.",
    "Retailer listings within the Liquid Brun line.",
    0,1,[FA+"Liquid-Brun-94713.html"])
rel("French Avenue|Aether","Parfums de Marly|Greenly","INSPIRED_BY",
    0.78,0.80,0.76,0.74,0.80,0.60,
    "Reviewed as effectively identical to Parfums de Marly Greenly — green apple/bergamot over cedar-cashmeran-violet.",
    "Wearer blind-tests found them the same; a couple of sources, mostly enthusiast.",
    "Fragrantica + FragranceLovers naming Greenly as the dupe target.",
    0,0,[FA+"Aether-94702.html","https://fragrancelovers.com/products/french-avenue-by-fragrance-world-aether-greenly-dupe"])
rel("French Avenue|Atlantis Extrait","Simone Andreoli|Wavechild","INSPIRED_BY",
    0.58,0.58,0.58,0.56,0.75,0.40,
    "Coconut/watermelon/citrus with a cacao-ambergris base — a Wavechild-leaning fruity aquatic.",
    "Comparison inferred from the note profile; not a widely-cited dupe claim.",
    "Fragrantica profile; note-based inference.",
    0,1,[FA+"Atlantis-Extrait-113595.html"])
rel("French Avenue|Spectre Ghost","Nishane|Ani","INSPIRED_BY",
    0.74,0.74,0.74,0.72,0.72,0.60,
    "A well-known Nishane Ani clone — ginger/cardamom over pink pepper-rose with a sweet vanilla-cedar base.",
    "A touch simpler/sweeter than Ani.",
    "Fragrantica + Fragrenza roundup naming Ani.",
    0,0,[FA+"Spectre-Ghost-94697.html","https://www.fragrenza.com/blogs/fragrances/spectre-ghost-by-french-avenue-mysterious-woody-and-elegant-scents"])
rel("French Avenue|Spectre Wraith","Kilian|Black Phantom","INSPIRED_BY",
    0.74,0.72,0.74,0.76,0.75,0.58,
    "Rum/coffee/sugarcane profile reviewed as a Kilian Black Phantom clone.",
    "Slightly boozier-sweet than Black Phantom.",
    "Fragrantica + retailer (My Smell Shop) + TikTok naming Black Phantom.",
    0,0,[FA+"Spectre-Wraith-94699.html","https://mysmellshop.com/products/french-avenue-spectre-wraith-edp-clone-black-phantom-by-kilian"])
rel("French Avenue|Spectre Pinnace","Louis Vuitton|Pacific Chill","INSPIRED_BY",
    0.60,0.65,0.58,0.52,0.60,0.35,
    "Recorded on the 'Pinnace' reading — a bitter-lemon Louis Vuitton Pacific Chill clone.",
    "NAME AMBIGUITY: 'Spectre Pinnace' is not a confirmed single release; likely conflates FA 'Spectre' (leather) and 'Pinnace' (Pacific Chill clone). Needs confirmation.",
    "Fragrantica 'Pinnace' profile ('clone of Pacific Chill').",
    0,1,[FA+"Pinnace-94701.html"])
rel("French Avenue|Pinnace Noir","Hugo Boss|Bottled","INSPIRED_BY",
    0.66,0.68,0.66,0.62,0.65,0.52,
    "A wearable, elegant take on the Hugo Boss Bottled apple-cinnamon DNA.",
    "More rounded/vanillic than the sharper original Bottled.",
    "Fragrantica reviews naming Boss Bottled DNA.",
    0,0,[FA+"Pinnace-Noir-94700.html"])
rel("French Avenue|Pinnace Oryn","Louis Vuitton|Afternoon Swim","INSPIRED_BY",
    0.70,0.74,0.66,0.62,0.60,0.55,
    "Widely recognised as an affordable Louis Vuitton Afternoon Swim alternative — mandarin/orange/bergamot over ginger and ambergris.",
    "A touch less radiant/expensive-smelling than the LV.",
    "Fragrantica + Parfumo naming Afternoon Swim.",
    0,0,[FA+"Pinnace-Oryn-101170.html","https://www.parfumo.com/Perfumes/french-avenue/pinnace-oryn"])
rel("French Avenue|Azzure Oud","Maison Crivelli|Oud Maracuja","INSPIRED_BY",
    0.80,0.82,0.80,0.78,0.78,0.62,
    "Reviewed as a ~96% Maison Crivelli Oud Maracuja clone — passionfruit/saffron over oud with a leather-guaiac-amber base.",
    "A hair less refined than the niche original.",
    "Fragrantica + retailer (Rimal Al Misk, My Smell Shop) naming Oud Maracuja.",
    0,0,[FA+"Azzure-Oud-94714.html","https://rimalalmisk.com/products/french-avenue-azzure-aoud"])
rel("French Avenue|Cocoa Morado","Maison Crivelli|Oud Cadenza","INSPIRED_BY",
    0.74,0.74,0.74,0.74,0.78,0.55,
    "Cinnamon/saffron/cardamom over dates-caramel-oud-incense — a Maison Crivelli Oud Cadenza clone.",
    "Sweeter/more caramelic than the original; single main source.",
    "Fragrantica + YouTube reviews naming Oud Cadenza.",
    0,1,[FA+"Cocoa-Morado-98886.html"])

# French Avenue ORIGINAL_DNA / ambiguous
rel("French Avenue|Royal Blend Bourbon","French Avenue|Royal Blend Bourbon","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Boozy whiskey aromatic (cinnamon/basil over bourbon whiskey and lavender); no confirmed designer target.",
    "Original-leaning; any clone claim currently unsupported.",
    "Fragrantica profile.",
    0,1,[FA+"Royal-Blend-Bourbon-103478.html"])
rel("French Avenue|Royal Blend Vintage","French Avenue|Royal Blend Vintage","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Reviewed as a clone of 'Old Fashioned' (some say Single Malt), but the target house is unconfirmed — a boozy oriental fougere.",
    "Named target could not be pinned to a confirmed release; flagged.",
    "Fragrantica reviews.",
    0,1,[FA+"Royal-Blend-Vintage-103479.html"])
rel("French Avenue|Éclair Affair","French Avenue|Éclair Affair","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Creamy sweet gourmand with no confirmed designer target.",
    "Original-leaning gourmand.",
    "Fragrantica profile.",
    0,1,[FA+"Eclair-Affair-103338.html"])
rel("French Avenue|Meringue Luscious","French Avenue|Meringue Luscious","ORIGINAL_DNA",
    None,None,None,None,None,0.25,
    "NAME AMBIGUITY: appears to conflate FA 'Meringue' (a Crème de Cuir-leaning woody-floral-musk) and 'Luscious' (a pistachio gourmand compared to Lattafa Éclaire Pistache). No single confirmed product/target.",
    "Recorded on the pistachio-gourmand reading; product identity needs confirmation.",
    "Fragrantica 'Meringue' and 'Luscious' profiles.",
    0,1,[FA+"Luscious-94023.html","https://www.fragrantica.com/perfume/French-Avenue/Meringue-94024.html"])

if __name__ == "__main__":
    rep = b1.build_kb(
        extra_target_groups=[
            ("Rayhaan","AE",b2.RAYHAAN,2), ("Rasasi","AE",b2.RASASI,2),
            ("Arabiyat Prestige","AE",b3.ARAB,3),
            ("Arabiyat Prestige","AE",ARAB4,4), ("French Avenue","AE",FA4,4),
        ],
        extra_refs=b2.REFS2 + b3.REFS3 + REFS4,
        extra_rels=b2.R2 + b3.R3 + R4,
        batch_no=4,
        brands_covered=["Afnan","Lattafa","Rayhaan","Rasasi","Arabiyat Prestige","French Avenue"],
        report_name="coverage_report_batch4.json",
    )
    print(json.dumps(rep, indent=2, ensure_ascii=False))
