#!/usr/bin/env python3
"""
Noir Vault Fragrance KB — Batch 5 builder (FINAL).
Adds French Avenue cluster 2 (18) + Aromatix x French Avenue (10) = 28.
Completes the target catalogue. Prior batches pulled from their modules unchanged.
"""
import json
import build_batch4 as b4
b3 = b4.b3
b2 = b4.b2
b1 = b4.b1

# ===========================================================================
# FRENCH AVENUE  cluster 2 (18)
# ===========================================================================
FA5 = [
 dict(name="Essence de Blanc", g="unisex", c="EDP", y=2022, fam="Aromatic Tea",
      style="black tea citrus woody", lon="long", proj="strong",
      prof="Citrus/ginger/neroli/cinnamon over a black-tea-ambroxan-incense-guaiac base — a black-tea-heavy Louis Vuitton Imagination take.",
      acc=["citrus","tea","aromatic","woody","incense"],
      top=["orange","lemon","bergamot"], heart=["ginger","neroli","cinnamon"],
      base=["black tea","ambroxan","incense","guaiac wood"]),
 dict(name="Essence de Matcha", g="unisex", c="EDP", y=2024, fam="Woody Aromatic",
      style="green tea fig woody", lon="moderate", proj="moderate",
      prof="Orange/lemon/fig over matcha tea-apricot-osmanthus with a sandalwood-cedar base; green-tea woody, no confirmed designer target.",
      acc=["tea","green","fruity","woody","fresh"],
      top=["orange","lemon","fig"], heart=["matcha tea","apricot","osmanthus"], base=["sandalwood","cedar"], nr=1),
 dict(name="Miraj Absolu", g="women", c="EDP", y=2024, fam="Floral Woody",
      style="animalic floral oud", lon="very long", proj="strong",
      prof="Almond/mandarin/watery over civet-rose-gardenia with an oud-coffee-vanilla-patchouli-amber base — the best-regarded PdM Layton Exclusif alternative.",
      acc=["floral","woody","oud","animalic","sweet"],
      top=["almond","mandarin","bergamot","watery notes"], heart=["civet","geranium","rose","gardenia","water lily"],
      base=["guaiac wood","oud","vanilla","coffee","sandalwood","patchouli","amber","oakmoss","pink pepper"]),
 dict(name="Miraj Exclusif", g="women", c="EDP", y=2024, fam="Oriental Oud",
      style="coffee jasmine oud", lon="long", proj="strong",
      prof="Cardamom/coffee over jasmine sambac with an oud-vanilla-incense base — a more oriental, sensual Penhaligon's The Bewitching Yasmine interpretation.",
      acc=["oud","coffee","floral","incense","sweet"],
      top=["cardamom","coffee"], heart=["jasmine sambac"], base=["oud","vanilla","incense"]),
 dict(name="Moonstone Bleu", g="unisex", c="EDP", y=2024, fam="Aromatic Leather",
      style="aldehydic beeswax leather", lon="long", proj="strong",
      prof="Aldehydes/metallic/violet-leaf over lavender-beeswax-lime-leather with a musk-honey-oakmoss-woody base — a Penhaligon's Sartorial clone.",
      acc=["aromatic","leather","powdery","honey","woody"],
      top=["aldehydes","metallic notes","violet leaf","black pepper","cardamom"],
      heart=["lavender","beeswax","lime","leather","cyclamen"],
      base=["white musk","honey","oakmoss","patchouli","cedar","tonka bean","vanilla","amber","myrrh"]),
 dict(name="Moonstone Noire", g="unisex", c="EDP", y=2024, fam="Leather",
      style="smoky leather", lon="long", proj="strong",
      prof="Smoky top over cedar-vetiver-balms with a vanilla-ambernat-leather-white-oud base — close to Tom Ford Ombre Leather.",
      acc=["leather","smoky","woody","amber","warm spicy"],
      top=["smoky notes"], heart=["cedar","vetiver","balsamic notes"], base=["vanilla","ambernat","leather","oud"]),
 dict(name="Vulcan Feu", g="unisex", c="EDP", y=2025, fam="Fruity Chypre",
      style="fruity praline chypre", lon="long", proj="strong",
      prof="Mango/lemon/ginger/rhubarb over pink pepper-jasmine-violet-praline with a tonka-cedar-ambergris-moss base; reviewers cite a niche 'God of Fire' (house unconfirmed).",
      acc=["fruity","chypre","sweet","warm spicy","woody"],
      top=["mango","lemon","ginger","rhubarb"], heart=["pink pepper","jasmine","violet","praline"],
      base=["tonka bean","cedar","ambergris","oakmoss"], nr=1),
 dict(name="Vulcan Black Friday", g="men", c="EDP", y=2025, fam="Leather",
      style="spicy leather", lon="very long", proj="strong",
      prof="Saffron/apple/cinnamon over leather-rose with a patchouli-moss-musk-papyrus base — inspired by Xerjoff Deified (Tony Iommi).",
      acc=["leather","warm spicy","woody","smoky","fruity"],
      top=["saffron","apple","cinnamon"], heart=["leather","rose"], base=["patchouli","oakmoss","musk","papyrus"]),
 dict(name="Vulcan Baie", g="unisex", c="EDP", y=2025, fam="Fruity",
      style="boozy berry", lon="long", proj="strong",
      prof="Blackberry/blackcurrant/rosemary over raspberry-vodka-basil with a strawberry-musk-peach-amber base — a Stephane Humbert Lucas Pink Boa dupe.",
      acc=["fruity","boozy","sweet","musky","green"],
      top=["blackberry","black currant","rosemary","bergamot"], heart=["raspberry","vodka accord","basil","lily-of-the-valley"],
      base=["strawberry","musk","peach","amber","sandalwood","patchouli","incense"]),
 dict(name="Vulcan Sable", g="unisex", c="EDP", y=2025, fam="Woody Spicy",
      style="whiskey spiced woody", lon="long", proj="strong",
      prof="Whiskey/coriander/mandarin with sesame-anise over deep woods; boozy spiced woody, no confirmed designer target.",
      acc=["boozy","warm spicy","woody","aromatic","amber"],
      top=["whiskey accord","coriander","mandarin"], heart=["sesame","anise"], base=["woods","amber"], nr=1),
 dict(name="Zenith Blue", g="men", c="EDP", y=2025, fam="Aromatic Fougere",
      style="ambroxan fresh spicy", lon="long", proj="strong",
      prof="Bergamot/elemi over pepper-lavender-geranium with an ambroxan-vetiver-patchouli base — reviewed as the best Dior Sauvage EDT dupe (ambroxan-bomb era).",
      acc=["fresh spicy","ambroxan","citrus","aromatic","woody"],
      top=["bergamot","elemi"], heart=["pepper","lavender","geranium"], base=["ambroxan","vetiver","patchouli"]),
 dict(name="Zenith Santal", g="unisex", c="EDP", y=2025, fam="Woody",
      style="creamy sandalwood spicy", lon="long", proj="strong",
      prof="Saffron over chestnut-lavender with a sandalwood-vanilla-cedar base — a 1:1 Emporio Armani Stronger With You Sandalwood clone, stronger-performing.",
      acc=["woody","creamy","sweet","warm spicy","amber"],
      top=["saffron"], heart=["chestnut","lavender"], base=["sandalwood","vanilla","cedar"]),
 dict(name="Zenith Vanilla", g="unisex", c="EDP", y=2025, fam="Amber Vanilla",
      style="sweet vanilla", lon="long", proj="moderate",
      prof="Zenith-line sweet vanilla; detailed pyramid not documented in reviewed sources.",
      acc=["sweet","vanilla","amber","gourmand"], nr=1),
 dict(name="Zenith Tobacco", g="unisex", c="EDP", y=2025, fam="Amber Vanilla Tobacco",
      style="chocolate honey tobacco", lon="long", proj="strong",
      prof="Chocolate/mandarin over honey-patchouli-caramel with a tolu-tonka-moss base — a Dior Tobacolor clone.",
      acc=["sweet","tobacco","gourmand","warm spicy","amber"],
      top=["chocolate","mandarin"], heart=["honey","patchouli","caramel"], base=["tolu balsam","tonka bean","oakmoss"]),
 dict(name="Zenith Deep", g="men", c="EDP", y=2025, fam="Aromatic Woody",
      style="fresh woody incense", lon="long", proj="strong",
      prof="Grapefruit/pepper/mint over ginger-melon-nutmeg-jasmine with an incense-sandalwood-amber-cedar-labdanum base — a favoured Bleu de Chanel (L'Exclusif) dupe.",
      acc=["citrus","aromatic","woody","incense","fresh"],
      top=["grapefruit","pepper","lemon","mint","bergamot"], heart=["ginger","melon","nutmeg","jasmine"],
      base=["incense","sandalwood","amber","cedar","labdanum"]),
 dict(name="Veneno", g="unisex", c="EDP", y=2025, fam="Amber Woody",
      style="smoky apple tobacco", lon="long", proj="strong",
      prof="Apple/smoke/cinnamon over tobacco-moss with a bourbon-vanilla-Orcanox base; smoky-fruity amber, no confirmed designer target.",
      acc=["smoky","fruity","tobacco","sweet","amber"],
      top=["apple","smoke","cinnamon"], heart=["tobacco","oakmoss"], base=["bourbon vanilla","orcanox"], nr=1),
 dict(name="Veneno Bianco", g="unisex", c="EDP", y=2025, fam="Floral Coconut",
      style="creamy coconut floral", lon="long", proj="moderate",
      prof="Neroli/milk/bergamot over white flowers-tiare-ylang with a coconut-vanilla-labdanum-guaiac base; creamy tropical floral, no confirmed target.",
      acc=["floral","coconut","creamy","sweet","tropical"],
      top=["neroli","milk","bergamot"], heart=["white flowers","tiare","ylang-ylang"],
      base=["coconut","vanilla","labdanum","guaiac wood"], nr=1),
 dict(name="Veneno Scarlet", g="unisex", c="Extrait", y=2025, fam="Fruity Leather",
      style="berry caramel leather", lon="very long", proj="strong",
      prof="Strawberry/blackberry/caramel over raspberry-cedar-cinnamon with a leather-patchouli-tonka-vanilla base — a Stephane Humbert Lucas Venom Incarnat dupe.",
      acc=["fruity","leather","sweet","gourmand","warm spicy"],
      top=["strawberry","blackberry","caramel"], heart=["raspberry","cedar","cinnamon"],
      base=["leather","patchouli","fir","tonka bean","vanilla"]),
]

# ===========================================================================
# AROMATIX x FRENCH AVENUE (10)
# ===========================================================================
AROMATIX = [
 dict(name="Magnetiq", g="unisex", c="EDP", y=2025, fam="Woody Aromatic",
      style="fresh woody amber", lon="long", proj="strong",
      prof="Lavender/bergamot/pink pepper over orange blossom-iris-neroli with a cedar-amber-sandalwood-vanilla-myrrh base — a YSL MYSLF take with less citrus lift.",
      acc=["aromatic","woody","floral","amber","fresh"],
      top=["lavender","bergamot","pink pepper"], heart=["orange blossom","iris","musk","neroli","rosemary"],
      base=["cedar","amber","sandalwood","vanilla","myrrh","oakmoss"]),
 dict(name="Forbidden Fruit", g="unisex", c="EDP", y=2025, fam="Oriental Floral",
      style="fruity floral amber", lon="long", proj="strong",
      prof="Blood orange/bergamot/cardamom over red apple-peach-rose with a vanilla-amber-benzoin-cedar base; fruity oriental, no confirmed target.",
      acc=["fruity","floral","sweet","amber","warm spicy"],
      top=["blood orange","bergamot","cardamom"], heart=["red apple","peach","margarita accord","rose"],
      base=["vanilla","amber","benzoin","cedar","musk","sandalwood"], nr=1),
 dict(name="Naughty Dates", g="unisex", c="EDP", y=2025, fam="Amber Gourmand Coffee",
      style="coffee date gourmand", lon="long", proj="strong",
      prof="Cardamom/bergamot/mandarin over coffee-dates-honey-hazelnut-ebony with a caramel-vanilla-amber base; rich coffee-date gourmand, no confirmed designer target.",
      acc=["coffee","sweet","gourmand","warm spicy","amber"],
      top=["cardamom","bergamot","mandarin"], heart=["coffee","dates","honey","hazelnut","ebony wood","cinnamon"],
      base=["caramel","vanilla","amber","sandalwood"], nr=1),
 dict(name="Carnal Desire", g="unisex", c="EDP", y=2024, fam="Fruity Leather Oud",
      style="candied leather oud", lon="long", proj="strong",
      prof="Raspberry/cinnamon over cotton-candy-orris-rose with a leather-oud-cedar-patchouli-vanilla base — a candied take reviewers link to Oud Maracuja / SHL Cuir InfraRouge, but held as its own creation.",
      acc=["fruity","leather","oud","sweet","gourmand"],
      top=["raspberry","cinnamon","bergamot"], heart=["cotton candy","orris","rose"],
      base=["leather","oud","cedar","patchouli","vanilla"], nr=1),
 dict(name="Teas Me", g="unisex", c="EDP", y=2025, fam="Woody Tea",
      style="black tea aromatic", lon="long", proj="moderate",
      prof="Ginger/lime over black tea-hedione-cardamom-geranium with an olibanum-amber-tonka-patchouli-vanilla base; tea-woody, no confirmed designer target.",
      acc=["tea","woody","aromatic","fresh","warm spicy"],
      top=["ginger","lime"], heart=["black tea","hedione","cardamom","geranium"],
      base=["olibanum","amber","tonka bean","patchouli","vanilla"], nr=1),
 dict(name="Frostbite", g="unisex", c="EDP", y=2025, fam="Fruity Aromatic",
      style="fresh fruity spicy", lon="long", proj="strong",
      prof="Blueberry/mango/apple/bergamot/cardamom over lavender-geranium-violet-jasmine-pink pepper with an ambergris-vanilla-amber-sandalwood base; fresh fruity-aromatic, no confirmed target.",
      acc=["fruity","aromatic","fresh","sweet","woody"],
      top=["blueberry","mango","apple","bergamot","cardamom"], heart=["lavender","geranium","violet","jasmine","pink pepper","vetiver"],
      base=["ambergris","vanilla","amber","sandalwood","oakmoss","cedar","patchouli"], nr=1),
 dict(name="Platine Blanc", g="unisex", c="EDP", y=2025, fam="Aromatic Green",
      style="minty gin-tonic fresh", lon="moderate", proj="moderate",
      prof="Mint/lime/tonic-water/lemon over rosemary-blackcurrant-jasmine with a musk-ambergris-sandalwood-oakmoss base; reviewers cite 'Torino 21' (house unconfirmed).",
      acc=["fresh","green","aromatic","citrus","musky"],
      top=["mint","lime","tonic water","lemon"], heart=["rosemary","black currant","jasmine"],
      base=["musk","ambergris","sandalwood","oakmoss"], nr=1),
 dict(name="L'Absolu Noir", g="unisex", c="EDP", y=2025, fam="Amber Woody",
      style="dark amber woody", lon="long", proj="strong",
      prof="Aromatix collab 'dark' composition; detailed pyramid and any designer target not documented in reviewed sources.",
      acc=["amber","woody","smoky","warm spicy"], nr=1),
 dict(name="Midnight Oud", g="unisex", c="EDP", y=2024, fam="Woody Oud",
      style="dark oud", lon="long", proj="strong",
      prof="Aromatix collab oud composition; detailed pyramid and any designer target not documented in reviewed sources.",
      acc=["oud","woody","amber","smoky"], nr=1),
 dict(name="Élara", g="women", c="EDP", y=2025, fam="Floral",
      style="floral", lon="moderate", proj="moderate",
      prof="Aromatix collab floral; detailed pyramid and any designer target not documented in reviewed sources.",
      acc=["floral","sweet","fresh","musky"], nr=1),
]

# ===========================================================================
# NEW REFERENCE TARGETS for Batch 5
# ===========================================================================
REFS5 = [
 dict(brand="Parfums de Marly", name="Layton Exclusif", fam="Floral Woody",
      acc=["floral","woody","oud","animalic","sweet"],
      top=["almond","mandarin"], heart=["civet","rose","geranium"], base=["oud","vanilla","coffee","patchouli"]),
 dict(brand="Penhaligon's", name="The Bewitching Yasmine", fam="Floral",
      acc=["floral","sweet","fruity","musky"],
      top=["pink pepper","davana"], heart=["jasmine sambac","rose"], base=["vanilla","tonka bean","musk"]),
 dict(brand="Penhaligon's", name="Sartorial", fam="Aromatic Leather",
      acc=["aromatic","leather","honey","powdery","woody"],
      top=["aldehydes","violet leaf","black pepper"], heart=["beeswax","lavender","leather"],
      base=["oakmoss","cedar","tonka bean","gurjan balsam","myrrh"]),
 dict(brand="Stephane Humbert Lucas 777", name="Pink Boa", fam="Fruity",
      acc=["fruity","boozy","sweet","musky","green"],
      top=["blackberry","black currant"], heart=["raspberry","vodka accord"], base=["strawberry","musk","amber"]),
 dict(brand="Stephane Humbert Lucas 777", name="Venom Incarnat", fam="Fruity Leather",
      acc=["fruity","leather","sweet","gourmand","warm spicy"],
      top=["strawberry","raspberry","caramel"], heart=["cedar","cinnamon"], base=["leather","patchouli","tonka bean","vanilla"]),
 dict(brand="Xerjoff", name="Deified", fam="Leather",
      acc=["leather","warm spicy","woody","smoky","fruity"],
      top=["saffron","apple","cinnamon"], heart=["leather","rose"], base=["patchouli","oakmoss","papyrus"]),
 dict(brand="Emporio Armani", name="Stronger With You Sandalwood", fam="Woody",
      acc=["woody","creamy","sweet","warm spicy","amber"],
      top=["saffron"], heart=["chestnut","lavender"], base=["sandalwood","vanilla","cedar"]),
 dict(brand="Dior", name="Tobacolor", fam="Amber Vanilla Tobacco",
      acc=["sweet","tobacco","gourmand","warm spicy","amber"],
      top=["mandarin"], heart=["honey","patchouli","tobacco"], base=["tolu balsam","tonka bean","vanilla"]),
 dict(brand="Yves Saint Laurent", name="MYSLF", fam="Amber Floral",
      acc=["floral","woody","aromatic","amber","fresh"],
      top=["bergamot"], heart=["orange blossom"], base=["patchouli","ambrofix","woods"]),
]

# ===========================================================================
# BATCH-5 RELATIONSHIPS
# ===========================================================================
R5 = []
def rel(frm,to,typ,ov,op,he,dr,pe,cc,reason,honest,evid,ver,nr,srcs):
    R5.append(dict(frm=frm,to=to,typ=typ,ov=ov,op=op,he=he,dr=dr,pe=pe,cc=cc,
        reason=reason,honest=honest,evid=evid,ver=ver,nr=nr,srcs=srcs,batch=5))
FA="https://www.fragrantica.com/perfume/French-Avenue/"
AX="https://www.fragrantica.com/perfume/Aromatix-X-French-Avenue/"

# ---- French Avenue cluster 2 ----
rel("French Avenue|Essence de Blanc","Louis Vuitton|Imagination","INSPIRED_BY",
    0.70,0.72,0.68,0.66,0.72,0.55,
    "A black-tea-heavy Louis Vuitton Imagination interpretation — citrus/ginger/neroli over black tea, ambroxan and guaiac.",
    "Heavier on black tea/incense than Imagination; sits among several Imagination clones.",
    "Fragrantica + Parfumo reviews placing it in the Imagination clone cluster.",
    0,0,[FA+"Essence-de-Blanc-95181.html","https://www.parfumo.com/Perfumes/french-avenue/essence-de-blanc"])
rel("French Avenue|Miraj Absolu","Parfums de Marly|Layton Exclusif","INSPIRED_BY",
    0.76,0.74,0.76,0.78,0.80,0.62,
    "Regarded as the best-performing Parfums de Marly Layton Exclusif alternative at a fraction of the price.",
    "Critics note the dupes don't fully capture Layton Exclusif's animalic depth.",
    "Fragrantica + Parfumo + decant listings naming Layton Exclusif.",
    0,0,[FA+"Miraj-Absolu-94709.html","https://www.parfumo.com/Perfumes/french-avenue/miraj-absolu"])
rel("French Avenue|Miraj Exclusif","Penhaligon's|The Bewitching Yasmine","INSPIRED_BY",
    0.62,0.60,0.64,0.62,0.70,0.48,
    "A more oriental, sensual interpretation of Penhaligon's The Bewitching Yasmine — jasmine sambac with cardamom-coffee and oud.",
    "Adds oud/coffee darkness the original doesn't have; interpretation rather than clone.",
    "Fragrantica reviews naming The Bewitching Yasmine.",
    0,1,[FA+"Miraj-Exclusif-94710.html"])
rel("French Avenue|Moonstone Bleu","Penhaligon's|Sartorial","INSPIRED_BY",
    0.72,0.72,0.72,0.72,0.72,0.55,
    "A Penhaligon's Sartorial clone — aldehydic/metallic opening with beeswax, lavender and leather.",
    "A touch less refined than Sartorial's beeswax accord.",
    "Fragrantica + Parfumo naming Sartorial.",
    0,0,[FA+"Moonstone-Bleu-100011.html","https://www.parfumo.com/Perfumes/french-avenue/moonstone-bleu"])
rel("French Avenue|Moonstone Noire","Tom Ford|Ombre Leather","INSPIRED_BY",
    0.66,0.64,0.66,0.68,0.72,0.50,
    "Smoky leather profile reviewers find close to Tom Ford Ombre Leather.",
    "Slightly sweeter/oudier drydown than Ombre Leather; some cite other leathers too.",
    "Fragrantica reviews naming Ombre Leather.",
    0,1,[FA+"Moonstone-Noire-100012.html"])
rel("French Avenue|Vulcan Baie","Stephane Humbert Lucas 777|Pink Boa","INSPIRED_BY",
    0.68,0.68,0.68,0.66,0.72,0.50,
    "A boozy-berry Stephane Humbert Lucas Pink Boa dupe — blackberry/raspberry/vodka over a fruity musky base.",
    "Niche target; a touch simpler than the SHL original.",
    "Fragrantica review feature naming SHL Pink Boa.",
    0,1,[FA+"Vulcan-Baie-110650.html","https://www.fragrantica.com/news/Vulcan-Baie-by-French-Avenue-Review-23673.html"])
rel("French Avenue|Vulcan Black Friday","Xerjoff|Deified","INSPIRED_BY",
    0.74,0.74,0.72,0.76,0.85,0.55,
    "Inspired by Xerjoff Deified (Tony Iommi) — saffron/apple/cinnamon over a leather-rose-papyrus base; strong performance.",
    "Very similar per reviewers; a hair less refined than the Xerjoff.",
    "Fragrantica + Bloom Perfumery naming Deified.",
    0,1,[FA+"Vulcan-Black-Friday-119220.html","https://bloomperfume.com/blogs/new-similar/vulcan-black-friday-by-french-avenue"])
rel("French Avenue|Zenith Blue","Dior|Sauvage Eau de Toilette","INSPIRED_BY",
    0.76,0.80,0.74,0.72,0.75,0.58,
    "Reviewed as the best Dior Sauvage EDT dupe — bergamot over pepper-lavender and an ambroxan-vetiver base (the ambroxan-bomb era).",
    "Slightly less cold/peppery than the original Sauvage.",
    "Fragrantica + Discovery Decants naming Sauvage EDT.",
    0,0,[FA+"Zenith-Blue-106865.html","https://discoverydecants.com/products/french-avenue-zenith-blue"])
rel("French Avenue|Zenith Santal","Emporio Armani|Stronger With You Sandalwood","INSPIRED_BY",
    0.82,0.82,0.82,0.84,0.82,0.62,
    "Reviewed as a 1:1 Emporio Armani Stronger With You Sandalwood clone — saffron/chestnut over a creamy sandalwood-vanilla base.",
    "Reported as stronger-projecting than the original; single main source.",
    "Fragrantica + Parfumo naming SWY Sandalwood.",
    0,1,[FA+"Zenith-Santal-120869.html","https://www.parfumo.com/Perfumes/french-avenue/zenith-santal"])
rel("French Avenue|Zenith Tobacco","Dior|Tobacolor","INSPIRED_BY",
    0.72,0.70,0.72,0.74,0.75,0.52,
    "A Dior Tobacolor clone — chocolate/mandarin over honey-patchouli-caramel with a tolu-tonka base.",
    "Sweeter/more chocolatey than the original; single main source.",
    "Fragrantica + retailer listings naming Tobacolor.",
    0,1,[FA+"ZENITH-TOBACCO-106863.html"])
rel("French Avenue|Zenith Deep","Chanel|Bleu de Chanel","INSPIRED_BY",
    0.74,0.74,0.72,0.72,0.75,0.60,
    "A favoured Bleu de Chanel (L'Exclusif) dupe — grapefruit/mint over ginger-nutmeg with an incense-sandalwood base.",
    "Community places it among the top BdC clones; a hair less refined than the Chanel.",
    "Fragrantica + Parfumo reviews naming Bleu de Chanel.",
    0,0,[FA+"Zenith-Deep-120870.html","https://www.parfumo.com/Perfumes/french-avenue/zenith-deep"])
rel("French Avenue|Veneno Scarlet","Stephane Humbert Lucas 777|Venom Incarnat","INSPIRED_BY",
    0.72,0.72,0.72,0.72,0.80,0.52,
    "Inspired by Stephane Humbert Lucas Venom Incarnat — strawberry/caramel over a leather-patchouli-tonka base.",
    "Niche target; a touch more gourmand than the SHL original.",
    "Fragrantica + ScentAdvice naming SHL Venom Incarnat.",
    0,1,[FA+"Veneno-Scarlet-110648.html","https://scentadvice.com/veneno-scarlet-2025-french-avenue/"])
rel("French Avenue|Essence de Matcha","French Avenue|Essence de Matcha","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Green-tea/fig woody with no confirmed designer target.",
    "Original-leaning matcha woody.",
    "Fragrantica + Parfumo profiles.",
    0,1,[FA+"Essence-de-Matcha-98888.html"])
rel("French Avenue|Vulcan Feu","French Avenue|Vulcan Feu","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Fruity-praline chypre reviewers link to a niche 'God of Fire', but that target house could not be confirmed.",
    "Named target unverifiable; stored as original DNA with closest profile.",
    "Fragrantica reviews.",
    0,1,[FA+"Vulcan-Feu-105520.html"])
rel("French Avenue|Vulcan Sable","French Avenue|Vulcan Sable","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Boozy whiskey-spiced woody with no confirmed designer target.",
    "Original-leaning boozy woody.",
    "Fragrantica profile.",
    0,1,[FA+"Vulcan-Feu-105520.html"])
rel("French Avenue|Zenith Vanilla","French Avenue|Zenith Vanilla","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Zenith-line sweet vanilla; pyramid and any target not documented.",
    "Awaiting a documented note pyramid.",
    "Fragrantica designer listing.",
    0,1,["https://www.fragrantica.com/designers/French-Avenue.html"])
rel("French Avenue|Veneno","French Avenue|Veneno","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Smoky-apple-tobacco amber with no confirmed designer target.",
    "Original-leaning smoky amber.",
    "Fragrantica profile.",
    0,1,[FA+"Veneno-105519.html"])
rel("French Avenue|Veneno Bianco","French Avenue|Veneno Bianco","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Creamy coconut-white-floral with no confirmed designer target.",
    "Original-leaning tropical floral.",
    "Fragrantica profile.",
    0,1,[FA+"Veneno-Bianco-105518.html"])

# ---- Aromatix x French Avenue ----
rel("Aromatix × French Avenue|Magnetiq","Yves Saint Laurent|MYSLF","INSPIRED_BY",
    0.66,0.62,0.68,0.66,0.75,0.50,
    "Reads as a YSL MYSLF interpretation — orange-blossom floral-woody amber with less of the bright citrus opening.",
    "Tones down MYSLF's citrus lift; more myrrh/oakmoss depth.",
    "Fragrantica reviews naming MYSLF.",
    0,1,[AX+"Magnetiq-117529.html"])
rel("Aromatix × French Avenue|Carnal Desire","Maison Crivelli|Oud Maracuja","SIMILAR_DNA",
    0.55,0.55,0.55,0.55,0.72,0.42,
    "A candied take reviewers link to Oud Maracuja (and SHL Cuir InfraRouge) — raspberry/cotton-candy over a leather-oud base.",
    "One reviewer stresses it's an original standalone that merely resembles those; not a clone.",
    "Fragrantica reviews naming Oud Maracuja / Cuir InfraRouge.",
    0,1,[AX+"Carnal-Desire-99331.html"])
for nm,reason,src in [
 ("Forbidden Fruit","Fruity oriental floral with no confirmed designer target.","Forbidden-Fruit-117531.html"),
 ("Naughty Dates","Rich coffee-date gourmand with no confirmed designer target.","Naughty-Dates-122285.html"),
 ("Teas Me","Black-tea woody with no confirmed designer target.","Teas-Me-117532.html"),
 ("Frostbite","Fresh fruity-aromatic with no confirmed designer target.","Frostbite-123532.html"),
 ("Platine Blanc","Minty gin-tonic fresh reviewers link to a niche 'Torino 21' (house unconfirmed).","Platine-Blanc-106068.html"),
 ("L'Absolu Noir","Dark amber-woody; pyramid and any target not documented.","../../designers/Aromatix-X-French-Avenue.html"),
 ("Midnight Oud","Dark oud; pyramid and any target not documented.","../../designers/Aromatix-X-French-Avenue.html"),
 ("Élara","Floral; pyramid and any target not documented.","../../designers/Aromatix-X-French-Avenue.html"),
]:
    rel(f"Aromatix × French Avenue|{nm}", f"Aromatix × French Avenue|{nm}", "ORIGINAL_DNA",
        None,None,None,None,None,0.30,
        f"No cross-validated designer/niche inspiration: {reason} Stored as original DNA with closest profile where available.",
        "Inspiration unverified — flagged for a later deepening pass.",
        "Fragrantica profiles; no confirmed clone target.",
        0,1,[AX+src])

if __name__ == "__main__":
    rep = b1.build_kb(
        extra_target_groups=[
            ("Rayhaan","AE",b2.RAYHAAN,2), ("Rasasi","AE",b2.RASASI,2),
            ("Arabiyat Prestige","AE",b3.ARAB,3),
            ("Arabiyat Prestige","AE",b4.ARAB4,4), ("French Avenue","AE",b4.FA4,4),
            ("French Avenue","AE",FA5,5), ("Aromatix × French Avenue","AE",AROMATIX,5),
        ],
        extra_refs=b2.REFS2 + b3.REFS3 + b4.REFS4 + REFS5,
        extra_rels=b2.R2 + b3.R3 + b4.R4 + R5,
        batch_no=5,
        brands_covered=["Afnan","Lattafa","Rayhaan","Rasasi","Arabiyat Prestige",
                        "French Avenue","Aromatix × French Avenue"],
        report_name="coverage_report_batch5.json",
    )
    print(json.dumps(rep, indent=2, ensure_ascii=False))
