#!/usr/bin/env python3
"""
Noir Vault Fragrance KB — Batch 3 builder (Arabiyat Prestige, part 1 of 2: first 30).
Extends the same DB via the shared engine. Batches 1+2 data are pulled from their
modules unchanged; Batch 3 adds Arabiyat Prestige #1-30 (Aariz .. Marwa).
"""
import json
import build_batch2 as b2
b1 = b2.b1

# ---------------------------------------------------------------------------
# ARABIYAT PRESTIGE — first 30 (Aariz through Marwa)
# ---------------------------------------------------------------------------
ARAB = [
 dict(name="Aariz", g="unisex", c="EDP", y=2024, fam="Amber Gourmand",
      style="sweet spicy gourmand", lon="long", proj="moderate",
      prof="Base Aariz: a warm sweet-spicy gourmand in the Aariz Intense / Khamrah lane. Precise pyramid not documented.",
      acc=["sweet","gourmand","warm spicy","vanilla","amber"], nr=1),
 dict(name="Aariz Intense", g="unisex", c="EDP", y=2023, fam="Amber Gourmand",
      style="boozy praline gourmand", lon="long", proj="strong",
      prof="Cardamom/fig-leaf opening over lactonic praline and cedar with a tonka-vanilla-sandalwood base — a Khamrah-adjacent gourmand.",
      acc=["sweet","gourmand","warm spicy","vanilla","woody","boozy"],
      top=["cardamom","fig leaf"], heart=["cedar","lactonic notes","praline"],
      base=["tonka bean","vanilla","sandalwood"]),
 dict(name="Aariz L'Absolu", g="unisex", c="EDP", y=2024, fam="Amber Gourmand",
      style="rich gourmand", lon="long", proj="strong",
      prof="A richer 'absolu' flanker of Aariz; detailed pyramid not documented.",
      acc=["sweet","gourmand","vanilla","amber","warm spicy"], nr=1),
 dict(name="Al Noor", g="unisex", c="EDP", y=2025, fam="Woody Spicy",
      style="creamy tea-woody", lon="long", proj="moderate",
      prof="Cardamom/nutmeg/saffron over fig-iris-labdanum with a leather-tonka-patchouli base — a Gris Charnel-leaning woody.",
      acc=["woody","warm spicy","creamy","leather","sweet"],
      top=["cardamom","nutmeg","saffron"], heart=["fig","iris","labdanum","vetiver"],
      base=["leather","tonka bean","patchouli","vanilla"]),
 dict(name="Aristo", g="men", c="EDP", y=2025, fam="Floral Woody",
      style="fresh floral woody", lon="moderate", proj="moderate",
      prof="Ginger-flower/citrus opening over jasmine-magnolia-patchouli with a vanilla-musk-sandalwood base; no clear external target.",
      acc=["citrus","floral","woody","sweet","musky"],
      top=["ginger flower","mandarin","orange","lemon"], heart=["jasmine","magnolia","patchouli"],
      base=["vanilla","musk","sandalwood"], nr=1),
 dict(name="Ash'aa Mauve", g="women", c="EDP", y=2025, fam="Floral Fruity",
      style="berry floral", lon="moderate", proj="moderate",
      prof="Raspberry/rose/blueberry over violet-carnation-incense-neroli with a musk-cashmere-vanilla base; original-leaning.",
      acc=["fruity","floral","rose","sweet","powdery"],
      top=["raspberry","rose","blueberry"], heart=["violet","carnation","incense","neroli"],
      base=["musk","cashmere wood","vanilla"], nr=1),
 dict(name="Ash'aa Neroli", g="unisex", c="EDP", y=2025, fam="Citrus Floral",
      style="fresh citrus neroli", lon="moderate", proj="moderate",
      prof="Grapefruit/bergamot over verbena and neroli with an ambergris base; clean citrus-floral, original-leaning.",
      acc=["citrus","floral","fresh","aromatic","musky"],
      top=["grapefruit","bergamot"], heart=["verbena","neroli"], base=["ambergris"], nr=1),
 dict(name="Ash'aa Amethyst", g="women", c="EDP", y=2025, fam="Floral Fruity",
      style="floral fruity", lon="moderate", proj="moderate",
      prof="Ash'aa-line floral-fruity; detailed pyramid not documented.",
      acc=["floral","fruity","sweet","powdery"], nr=1),
 dict(name="Ash'aa Blanc", g="unisex", c="EDP", y=2025, fam="Floral Musk",
      style="clean white floral musk", lon="moderate", proj="moderate",
      prof="Ash'aa-line clean white-floral musk; detailed pyramid not documented.",
      acc=["floral","musky","clean","fresh"], nr=1),
 dict(name="Ash'aa Oud Noir", g="unisex", c="EDP", y=2024, fam="Aromatic Woody",
      style="green aromatic woody oud", lon="long", proj="strong",
      prof="Galbanum/juniper/citrus with peppermint-lavender-violet over oakmoss-ambroxan-amber-sandalwood-oud; green aromatic woody.",
      acc=["aromatic","woody","green","oud","fresh"],
      top=["galbanum","juniper berries","bergamot","lemon"], heart=["peppermint","lavender","violet"],
      base=["oakmoss","ambroxan","amber","sandalwood","cedar","oud"], nr=1),
 dict(name="Bedour", g="women", c="EDP", y=2023, fam="Fruity Gourmand",
      style="fruity floral gourmand", lon="moderate", proj="moderate",
      prof="Fruity-floral gourmand companion to Bedour Extrait; peach/citrus with a sweet cotton-candy-vanilla direction.",
      acc=["fruity","sweet","gourmand","floral","vanilla"], nr=1),
 dict(name="Bedour Extrait", g="women", c="Extrait", y=2023, fam="Fruity Gourmand",
      style="peachy cotton-candy gourmand", lon="long", proj="strong",
      prof="White peach/mandarin/bergamot over a gourmand accord, orange blossom and vetiver with a cotton-candy-akigalawood-vanilla-musk base.",
      acc=["fruity","sweet","gourmand","vanilla","floral"],
      top=["white peach","mandarin","bergamot"], heart=["gourmand accord","orange blossom","vetiver"],
      base=["cotton candy","akigalawood","vanilla","musk"]),
 dict(name="Blueberry Musk", g="unisex", c="EDP", y=2020, fam="Fruity Musk",
      style="berry musk", lon="moderate", proj="moderate",
      prof="Blueberry/blackberry over freesia-lavender-rose with a raspberry-vanilla-oakmoss-patchouli base; sweet fruity musk.",
      acc=["fruity","musky","sweet","floral"],
      top=["blueberry","blackberry"], heart=["freesia","lavender","rose"],
      base=["raspberry","vanilla","oakmoss","patchouli"], nr=1),
 dict(name="Cranberry Musk", g="unisex", c="EDP", y=2023, fam="Fruity Musk",
      style="berry musk", lon="moderate", proj="moderate",
      prof="Lotus/cranberry/freesia over musk-pear-jasmine with a sandalwood-vanilla base; fresh fruity musk.",
      acc=["fruity","musky","fresh","floral"],
      top=["lotus","cranberry","freesia"], heart=["musk","pear","jasmine"],
      base=["sandalwood","vanilla"], nr=1),
 dict(name="Hamdan The Brave", g="men", c="EDP", y=2024, fam="Amber Spicy",
      style="spicy warm", lon="long", proj="strong",
      prof="Opens close to Valentino Uomo Born in Roma Intense with a slight Sauvage Elixir edge; warm spicy-amber.",
      acc=["warm spicy","aromatic","amber","sweet","woody"], nr=1),
 dict(name="Hamdan The Hero", g="men", c="EDP", y=2024, fam="Aromatic Aquatic",
      style="fresh blue aromatic", lon="moderate", proj="moderate",
      prof="Citrus/pepper/cardamom with a calone-nutmeg-clove heart over cedar-musk-amber-patchouli — L'Eau d'Issey pour Homme DNA in a bluer key.",
      acc=["aquatic","aromatic","citrus","woody","fresh spicy"],
      top=["lemon","mandarin","pepper","cardamom"], heart=["nutmeg","orris","calone","clove"],
      base=["cedar","musk","amber","patchouli"]),
 dict(name="Hamdan The Sheikh", g="men", c="EDP", y=2024, fam="Aromatic Fougere",
      style="fresh spicy", lon="long", proj="strong",
      prof="Reviewed at ~85-90% of Dior Sauvage EDP/Parfum — a fresh-spicy ambroxan aromatic.",
      acc=["fresh spicy","ambroxan","aromatic","citrus","woody"],
      top=["bergamot","pepper"], heart=["lavender","sichuan pepper"], base=["ambroxan","cedar","amber"]),
 dict(name="Hypnotic Amber", g="unisex", c="EDP", y=2023, fam="Amber Woody",
      style="sweet woody smoky", lon="very long", proj="strong",
      prof="Bergamot/rose/incense over oud-patchouli-black pepper with a vanilla-ambroxan-musk base; a sweeter, ambery Aventus-adjacent woody.",
      acc=["amber","woody","sweet","smoky","incense"],
      top=["bergamot","rose","incense"], heart=["oud","patchouli","black pepper"],
      base=["vanilla","ambroxan","musk"], nr=1),
 dict(name="Hypnotic Oud", g="unisex", c="EDP", y=2023, fam="Amber Oud Gourmand",
      style="creamy oud gourmand", lon="long", proj="strong",
      prof="Clove/saffron/orange blossom over oud-akigalawood-caramel-cashmeran with a vanilla-amber base — a creamy Angels' Share-adjacent oud gourmand.",
      acc=["oud","sweet","gourmand","amber","warm spicy"],
      top=["clove","saffron","orange blossom"], heart=["oud","akigalawood","caramel","cashmeran"],
      base=["vanilla","amber"]),
 dict(name="Hypnotic Vanilla", g="unisex", c="EDP", y=2023, fam="Amber Vanilla",
      style="sweet vanilla amber", lon="long", proj="moderate",
      prof="Hypnotic-line sweet vanilla-amber; detailed pyramid not documented.",
      acc=["sweet","vanilla","amber","gourmand"], nr=1),
 dict(name="Ishatar Amber Vanilla", g="unisex", c="EDP", y=2023, fam="Amber Floral",
      style="caramel amber vanilla", lon="long", proj="strong",
      prof="Moroccan rose/mandarin/ginger/bergamot over caramel-amber-patchouli-jasmine with a vanilla-sandalwood-musk base; sweet amber floral.",
      acc=["amber","sweet","floral","vanilla","gourmand"],
      top=["moroccan rose","mandarin","ginger","bergamot"], heart=["caramel","amber","patchouli","jasmine"],
      base=["vanilla","amber","sandalwood","musk"], nr=1),
 dict(name="Ishatar Citrus Oud", g="unisex", c="EDP", y=2023, fam="Woody Oud",
      style="citrus amber oud", lon="long", proj="strong",
      prof="Bergamot/grapefruit over amber-patchouli-jasmine-oud with a cedar-tonka base; radiant citrus-woody-oud.",
      acc=["citrus","oud","woody","amber","fresh"],
      top=["bergamot","grapefruit"], heart=["amber","patchouli","jasmine","oud"], base=["cedar","tonka bean"], nr=1),
 dict(name="Ishatar Roses Vanilla", g="women", c="EDP", y=2023, fam="Floral Vanilla",
      style="rose vanilla", lon="moderate", proj="moderate",
      prof="Lemon over rose with a vanilla-white-musk-cedar base; bright romantic rose-vanilla.",
      acc=["floral","rose","sweet","vanilla","musky"],
      top=["lemon"], heart=["rose"], base=["vanilla","white musk","cedar"], nr=1),
 dict(name="Kohl Luminous", g="unisex", c="EDP", y=2025, fam="Fruity Chypre",
      style="fruity spicy sweet-woody", lon="long", proj="strong",
      prof="Lemon/mango/ginger/rhubarb over violet-jasmine-praline-pink pepper with an ambergris-moss-cedar-tonka base.",
      acc=["fruity","chypre","sweet","warm spicy","woody"],
      top=["lemon","mango","ginger","rhubarb"], heart=["violet","jasmine","praline","pink pepper"],
      base=["ambergris","oakmoss","cedar","tonka bean"], nr=1),
 dict(name="Kohl Opulence", g="unisex", c="EDP", y=2025, fam="Fruity Floral",
      style="pear floral amber", lon="long", proj="moderate",
      prof="Pear/bergamot/ginger over orange blossom-jasmine-woods with a musk-vanilla-amber base.",
      acc=["fruity","floral","sweet","amber","woody"],
      top=["pear","bergamot","ginger"], heart=["orange blossom","jasmine","woody notes"],
      base=["musk","vanilla","amber"], nr=1),
 dict(name="La Di Da For Him", g="men", c="EDP", y=2025, fam="Aromatic",
      style="fresh sweet aromatic", lon="moderate", proj="moderate",
      prof="Bergamot/grapefruit/geranium over tonka-aromatic-black pepper with a vanilla-ambergris-musk base; fresh-sweet aromatic, no clear external target.",
      acc=["citrus","aromatic","sweet","amber","musky"],
      top=["bergamot","grapefruit","geranium"], heart=["tonka bean","aromatic notes","black pepper"],
      base=["vanilla","ambergris","musk"], nr=1),
 dict(name="La Di Da For Her", g="women", c="EDP", y=2025, fam="Floral Gourmand",
      style="fruity vanilla gourmand", lon="long", proj="strong",
      prof="A brighter, red-fruit take on Tom Ford Vanilla Sex — sweet raspberry-lemon over tuberose-ylang-rose with a vanilla-benzoin-musk base.",
      acc=["sweet","vanilla","fruity","floral","gourmand"],
      top=["sweet notes","raspberry","lemon"], heart=["tuberose","ylang-ylang","rose"],
      base=["vanilla","benzoin","musk"]),
 dict(name="Lamsat Harir", g="women", c="EDP", y=2013, fam="Floral Fruity",
      style="fruity floral", lon="long", proj="moderate",
      prof="Grapes/blackcurrant over tuberose-jasmine-heliotrope with a musk-patchouli-cedar base; drydown reviewers find near-identical to Armani Sì Intense.",
      acc=["fruity","floral","sweet","chypre","powdery"],
      top=["grapes","black currant"], heart=["tuberose","jasmine","heliotrope"],
      base=["musk","patchouli","cedar"]),
 dict(name="Mahd Al Dhahab", g="unisex", c="EDP", y=2025, fam="Amber Woody",
      style="amber oud woody", lon="long", proj="strong",
      prof="Bergamot/spices/lemon over amber-patchouli-oud with a vanilla-sandalwood-musk base; one reviewer says it nearly matches Lattafa Teriaq Intense (in-house comparison, no designer target confirmed).",
      acc=["amber","woody","oud","sweet","warm spicy"],
      top=["bergamot","spices","lemon"], heart=["amber","patchouli","oud"],
      base=["vanilla","sandalwood","white musk"], nr=1),
 dict(name="Marwa", g="men", c="EDP", y=2025, fam="Woody Spicy",
      style="spicy tea woody", lon="long", proj="strong",
      prof="Bergamot/lemon/orange over ginger-cinnamon-neroli with an ambroxan-black tea-olibanum-guaiac base — a Louis Vuitton Imagination-leaning spicy woody.",
      acc=["citrus","warm spicy","woody","tea","amber"],
      top=["bergamot","lemon","orange"], heart=["ginger","cinnamon","neroli"],
      base=["ambroxan","black tea","olibanum","guaiac wood"]),
]

# ---------------------------------------------------------------------------
# NEW REFERENCE TARGETS for Batch 3
# ---------------------------------------------------------------------------
REFS3 = [
 dict(brand="Louis Vuitton", name="Imagination", fam="Citrus Aromatic",
      acc=["citrus","aromatic","warm spicy","tea","woody"],
      top=["bergamot","lemon","orange"], heart=["ginger","cinnamon","neroli"], base=["ambroxan","black tea","guaiac wood"]),
 dict(brand="Giorgio Armani", name="Si", fam="Floral Fruity Chypre",
      acc=["fruity","floral","chypre","sweet","powdery"],
      top=["black currant","mandarin"], heart=["rose","freesia"], base=["patchouli","vanilla","woods"]),
 dict(brand="Dior", name="Sauvage Eau de Parfum", fam="Aromatic Fougere",
      acc=["fresh spicy","ambroxan","citrus","aromatic","sweet"],
      top=["bergamot","sichuan pepper"], heart=["lavender","star anise","nutmeg"], base=["ambroxan","vanilla","vetiver"]),
 dict(brand="Issey Miyake", name="L'Eau d'Issey pour Homme", fam="Aromatic Aquatic",
      acc=["aquatic","aromatic","citrus","woody","spicy"],
      top=["yuzu","bergamot","cardamom"], heart=["nutmeg","cinnamon","lily"], base=["cedar","tobacco","musk","amber"]),
 dict(brand="Valentino", name="Uomo Born in Roma Intense", fam="Amber Spicy",
      acc=["warm spicy","aromatic","amber","sweet","woody"],
      top=["sage","ginger"], heart=["violet","iris"], base=["vanilla","mineral notes","woods"]),
 dict(brand="Tom Ford", name="Vanilla Sex", fam="Amber Vanilla",
      acc=["sweet","vanilla","gourmand","spicy","amber"],
      top=["cinnamon","clove"], heart=["orchid","tuberose"], base=["vanilla","tonka bean","benzoin","musk"]),
]

# ---------------------------------------------------------------------------
# BATCH-3 RELATIONSHIPS
# ---------------------------------------------------------------------------
R3 = []
def rel(frm,to,typ,ov,op,he,dr,pe,cc,reason,honest,evid,ver,nr,srcs):
    R3.append(dict(frm=frm,to=to,typ=typ,ov=ov,op=op,he=he,dr=dr,pe=pe,cc=cc,
        reason=reason,honest=honest,evid=evid,ver=ver,nr=nr,srcs=srcs,batch=3))
AP = "https://www.fragrantica.com/perfume/Arabiyat-Prestige/"

rel("Arabiyat Prestige|Aariz Intense","Kilian|Angels' Share","INSPIRED_BY",
    0.62,0.60,0.63,0.66,0.75,0.55,
    "Marketed as inspired by Kilian Angels' Share — a boozy-praline-vanilla gourmand.",
    "Reviewers say it lands closer to Lattafa Khamrah than to Angels' Share itself; cardamom/fig-leaf opening differs from the cognac of the Kilian.",
    "Fragrantica + Parfumo reviews naming Angels' Share while noting the Khamrah resemblance.",
    0,0,[AP+"Aariz-Intense-103369.html","https://www.parfumo.com/Perfumes/arabiyat-prestige/aariz-intense"])
rel("Arabiyat Prestige|Aariz Intense","Lattafa|Khamrah","SIMILAR_DNA",
    0.68,0.66,0.70,0.70,0.78,0.55,
    "Community consensus places it in the same boozy-spiced-praline gourmand cluster as (and closer to) Lattafa Khamrah.",
    "Aariz Intense is a touch woodier/lactonic; both share the Angels' Share lineage.",
    "Fragrantica reviews explicitly comparing it to Khamrah.",
    0,0,[AP+"Aariz-Intense-103369.html"])
rel("Arabiyat Prestige|Al Noor","BDK Parfums|Gris Charnel","INSPIRED_BY",
    0.66,0.64,0.68,0.66,0.65,0.50,
    "Reviewed as close to Gris Charnel (Extrait) — cardamom/fig with a creamy tea-woody, leathery drydown.",
    "Al Noor adds more overt leather/labdanum; single main review source.",
    "Fragrantica review ('pretty close to gris charnel extrait').",
    0,1,[AP+"Al-Noor-115515.html"])
rel("Arabiyat Prestige|Marwa","Louis Vuitton|Imagination","INSPIRED_BY",
    0.70,0.72,0.68,0.66,0.70,0.55,
    "Reviewed/retailer-described as inspired by LV Imagination — citrus over ginger-cinnamon-neroli with a black-tea/ambroxan/guaiac base.",
    "A more affordable, slightly less airy Imagination.",
    "Discovery Decants + Parfumo + Fragrantica naming Imagination.",
    0,0,[AP+"Marwa-107084.html","https://www.parfumo.com/Perfumes/arabiyat-prestige/marwa"])
rel("Arabiyat Prestige|Lamsat Harir","Giorgio Armani|Si","INSPIRED_BY",
    0.66,0.60,0.66,0.72,0.65,0.50,
    "Reviewers find the drydown so close to Armani Sì Intense it's hard to tell apart — blackcurrant-fruity chypre with patchouli.",
    "Opening is fruitier (grapes); the Sì resemblance is strongest in the drydown.",
    "Fragrantica reviews naming Armani Sì Intense.",
    0,1,[AP+"Lamsat-Harir-48221.html"])
rel("Arabiyat Prestige|Hamdan The Sheikh","Dior|Sauvage Eau de Parfum","INSPIRED_BY",
    0.75,0.78,0.74,0.70,0.75,0.60,
    "Reviewed at ~85-90% of Dior Sauvage EDP/Parfum — a fresh-spicy ambroxan aromatic.",
    "A hair less refined and slightly shorter than genuine Sauvage EDP.",
    "Fragrantica + retailer descriptions naming Sauvage.",
    0,0,[AP+"Hamdan-The-Sheikh-103400.html"])
rel("Arabiyat Prestige|Hamdan The Hero","Issey Miyake|L'Eau d'Issey pour Homme","INSPIRED_BY",
    0.66,0.66,0.66,0.64,0.65,0.52,
    "Carries the unmistakable L'Eau d'Issey pour Homme DNA (calone/spice) in a bluer, fresher reading.",
    "Bluer/sweeter than the original Issey; a modern reinterpretation.",
    "Fragrantica reviews naming L'Eau d'Issey pour Homme.",
    0,0,[AP+"Hamdan-The-Hero-103398.html"])
rel("Arabiyat Prestige|Hamdan The Brave","Valentino|Uomo Born in Roma Intense","INSPIRED_BY",
    0.58,0.62,0.56,0.52,0.70,0.42,
    "Opens very close to Valentino Uomo Born in Roma Intense with a slight Sauvage Elixir facet.",
    "A two-way comparison (Valentino + Sauvage Elixir) — not a clean single-target clone.",
    "Fragrantica reviews.",
    0,1,[AP+"Hamdan-The-Brave-103399.html"])
rel("Arabiyat Prestige|Hypnotic Amber","Creed|Aventus","SIMILAR_DNA",
    0.48,0.52,0.46,0.44,0.80,0.40,
    "Often touted as an Aventus clone; in practice a sweeter, ambery, oud-tinged cousin rather than a close match.",
    "Reviewers agree it is 'related but not that close' — vanilla/ambroxan sweetness and oud pull it away from Aventus.",
    "Fragrantica reviews + YouTube ('touted as Aventus clone... not that close').",
    0,1,[AP+"Hypnotic-Amber-103366.html","https://www.youtube.com/watch?v=NBOI3x5Gacw"])
rel("Arabiyat Prestige|Hypnotic Oud","Kilian|Angels' Share","INSPIRED_BY",
    0.58,0.62,0.58,0.55,0.75,0.45,
    "One reviewer calls it the best dupe for the Angels' Share (Paradis) opening, just creamier.",
    "Saffron/clove and akigalawood give it an oud-gourmand twist distinct from the Kilian; single main source.",
    "Fragrantica review.",
    0,1,[AP+"Hypnotic-Oud-103368.html"])
rel("Arabiyat Prestige|La Di Da For Her","Tom Ford|Vanilla Sex","INSPIRED_BY",
    0.64,0.62,0.66,0.66,0.65,0.50,
    "Reviewed as a brighter, red-fruit take on Tom Ford Vanilla Sex — sweet raspberry-lemon into a vanilla-benzoin base.",
    "The strawberry/raspberry lift makes it fruitier than Vanilla Sex; not a 1:1.",
    "Fragrantica reviews + YouTube clone comparison.",
    0,0,[AP+"La-Di-Da-For-Her-115529.html","https://www.youtube.com/watch?v=GDeSW2T3VSw"])

# ---- ORIGINAL_DNA / awaiting stronger evidence (no confirmed designer target) ----
ORIG3 = {
 "Aariz":"Base Aariz gourmand; documented pyramid and any designer target unconfirmed.",
 "Aariz L'Absolu":"Richer Aariz flanker; pyramid/inspiration unconfirmed.",
 "Aristo":"Fresh floral-woody with no consensus designer target.",
 "Ash'aa Mauve":"Berry-floral described as an original Arabian-gardens composition.",
 "Ash'aa Neroli":"Clean citrus-neroli with no consensus designer target.",
 "Ash'aa Amethyst":"Ash'aa-line floral-fruity; pyramid/inspiration unconfirmed.",
 "Ash'aa Blanc":"Ash'aa-line white-floral musk; pyramid/inspiration unconfirmed.",
 "Ash'aa Oud Noir":"Green aromatic-woody-oud with no consensus designer target.",
 "Bedour":"Fruity-floral gourmand; no confirmed designer target.",
 "Bedour Extrait":"Peachy cotton-candy gourmand; no confirmed designer target.",
 "Blueberry Musk":"Sweet berry-musk; no confirmed designer target.",
 "Cranberry Musk":"Fresh berry-musk; no confirmed designer target.",
 "Hypnotic Vanilla":"Sweet vanilla-amber; pyramid/inspiration unconfirmed.",
 "Ishatar Amber Vanilla":"Sweet amber-floral gourmand; no confirmed designer target.",
 "Ishatar Citrus Oud":"Citrus-woody-oud; no confirmed designer target.",
 "Ishatar Roses Vanilla":"Rose-vanilla; no confirmed designer target.",
 "Kohl Luminous":"Fruity-spicy chypre; compared loosely to Lattafa dupes but no named designer target.",
 "Kohl Opulence":"Pear-floral-amber; no confirmed designer target.",
 "La Di Da For Him":"Fresh-sweet aromatic; no confirmed designer target.",
 "Mahd Al Dhahab":"Amber-oud woody; a reviewer likens it to Lattafa Teriaq Intense (in-house), but no designer target is confirmed.",
}
for nm,reason in ORIG3.items():
    rel(f"Arabiyat Prestige|{nm}", f"Arabiyat Prestige|{nm}", "ORIGINAL_DNA",
        None,None,None,None,None,0.30,
        f"No cross-validated designer/niche inspiration: {reason} Stored as original DNA with closest scent profile exposed.",
        "Inspiration unverified — flagged for a later deepening pass.",
        "Fragrantica/Parfumo/retailer profiles used for scent DNA; no confirmed clone target.",
        0,1,[AP])

if __name__ == "__main__":
    rep = b1.build_kb(
        extra_target_groups=[("Rayhaan","AE",b2.RAYHAAN,2), ("Rasasi","AE",b2.RASASI,2),
                             ("Arabiyat Prestige","AE",ARAB,3)],
        extra_refs=b2.REFS2 + REFS3,
        extra_rels=b2.R2 + R3,
        batch_no=3,
        brands_covered=["Afnan","Lattafa","Rayhaan","Rasasi","Arabiyat Prestige"],
        report_name="coverage_report_batch3.json",
    )
    print(json.dumps(rep, indent=2, ensure_ascii=False))
