#!/usr/bin/env python3
"""
Noir Vault Fragrance KB — Batch 2 builder (Rayhaan + Rasasi).
Extends the SAME database by re-running the shared engine in build_batch1 with
Batch-2 data appended. Batch-1 relationships are preserved exactly (single source
of truth is code). Includes the user-confirmed Turathi Blue -> Bvlgari Tygar fix
already applied in build_batch1.py.
"""
import json
import build_batch1 as b1

# ---------------------------------------------------------------------------
# RAYHAAN (18)
# ---------------------------------------------------------------------------
RAYHAAN = [
 dict(name="Elixir", g="unisex", c="EDP", y=2024, fam="Oriental Woody",
      style="sweet spicy woody", lon="long", proj="strong",
      prof="Sweet oriental-woody in the Le Male Elixir lane (lavender/vanilla/tobacco). Some reviewers instead cite Spicebomb — conflicting, flagged.",
      acc=["sweet","vanilla","warm spicy","tobacco","amber","lavender"],
      top=["lavender","bergamot"], heart=["cinnamon","tobacco"], base=["vanilla","tonka bean","benzoin","amber"], nr=1),
 dict(name="Imperia", g="men", c="EDP", y=2022, fam="Fruity Chypre",
      style="fruity smoky woody", lon="long", proj="strong",
      prof="Creed Aventus-style: citrus/apple/mint over jasmine-rose-patchouli with an oakmoss-amber-cedar base.",
      acc=["fruity","woody","chypre","fresh","smoky"],
      top=["bergamot","apple","mint"], heart=["jasmine","rose","patchouli","sandalwood"],
      base=["oakmoss","musk","amber","cedar"]),
 dict(name="Pacific", g="men", c="EDP", y=2022, fam="Citrus Aromatic",
      style="fresh citrus aquatic", lon="moderate", proj="moderate",
      prof="Citrus-aquatic in the Pacific Chill mould (note: dated 2022, predating Pacific Chill 2023 — timeline flagged).",
      acc=["citrus","fresh","aromatic","aquatic"],
      top=["citrus","mint"], heart=["basil"], base=["ambroxan","amber"], nr=1),
 dict(name="Pacific Aura", g="men", c="EDP", y=2025, fam="Citrus Aromatic",
      style="fresh citrus aquatic", lon="moderate", proj="moderate",
      prof="Widely praised near-1:1 Louis Vuitton Pacific Chill clone: mandarin-mint-citron over basil/carrot/rose and a fig-ambroxan base.",
      acc=["citrus","fresh","aromatic","green","aquatic"],
      top=["mandarin","mint","citron","bergamot","black currant","coriander"],
      heart=["basil","carrot","rose"], base=["fig","ambroxan","amber"]),
 dict(name="Pacific Aloha", g="unisex", c="EDP", y=2026, fam="Fruity Aquatic",
      style="sweet fruity marine", lon="moderate", proj="moderate",
      prof="Melon/watermelon/coconut summer scent reviewed as a Simone Andreoli Wavechild dupe.",
      acc=["fruity","sweet","aquatic","marine","coconut"],
      top=["melon","blood orange","lemon"], heart=["watermelon","coconut"],
      base=["marine notes","amberwood","cacao"], nr=1),
 dict(name="Azul", g="men", c="EDP", y=2026, fam="Aromatic Aquatic",
      style="clean citrus aquatic", lon="moderate", proj="moderate",
      prof="Clean lemon-bergamot-grapefruit-blossom citrus aquatic; reviewers loosely compare to Dior Homme Cologne.",
      acc=["citrus","aquatic","fresh","woody"],
      top=["lemon","bergamot"], heart=["grapefruit blossom"], base=["sandalwood","calone"], nr=1),
 dict(name="Ocean Rush", g="men", c="EDP", y=2024, fam="Aromatic Aquatic",
      style="fresh aquatic", lon="moderate", proj="moderate",
      prof="Aromatic-aquatic not tied to a single designer target; opening likened by some to Afnan 9AM Dive.",
      acc=["aquatic","aromatic","fresh","woody"],
      top=["calone","bergamot","mandarin"], heart=["lavender","cypress","rosemary"],
      base=["amber","musk","patchouli"], nr=1),
 dict(name="Lion", g="men", c="EDP", y=2024, fam="Amber Fougere",
      style="sweet spicy", lon="long", proj="strong",
      prof="Ultra Male-style sweet spicy: lavender/pear/mint over cinnamon-cumin and a vanilla-amber base.",
      acc=["sweet","warm spicy","vanilla","amber","lavender"],
      top=["lavender","pear","mint","bergamot"], heart=["cinnamon","clary sage","cumin"],
      base=["vanilla","amber","cedar","patchouli"]),
 dict(name="Tiger", g="men", c="EDP", y=2025, fam="Amber Spicy",
      style="spicy milky incense", lon="long", proj="strong",
      prof="Nishane Halfeti-style: nutmeg/clove/lemon over milk and rose with amber, patchouli, frankincense, labdanum.",
      acc=["warm spicy","incense","amber","creamy","woody"],
      top=["nutmeg","clove","lemon"], heart=["milk","rose","davana"],
      base=["amber","patchouli","frankincense","labdanum"]),
 dict(name="Panther", g="men", c="EDP", y=None, fam="Unverified (identity not confirmed)",
      style="unconfirmed", lon=None, proj=None,
      prof="Listed in target catalogue but not found on Fragrantica/Parfumo or any reviewed source under this name. Identity and scent data need manual confirmation before research.", nr=1),
 dict(name="Cobra", g="men", c="EDP", y=None, fam="Unverified (identity not confirmed)",
      style="unconfirmed", lon=None, proj=None,
      prof="Not found in research sources under 'Rayhaan Cobra' (note: Rasasi has a 'Hawas Kobra'). Identity needs manual confirmation.", nr=1),
 dict(name="Corium", g="men", c="EDP", y=2023, fam="Woody Leather",
      style="leather woody", lon="long", proj="strong",
      prof="~95% Emporio Armani Stronger With You Leather: chestnut/spice/elemi over sage with a vanilla-leather-oud base.",
      acc=["leather","woody","sweet","warm spicy"],
      top=["chestnut","spices","elemi"], heart=["sage"], base=["vanilla","leather","oud"]),
 dict(name="Crimson", g="men", c="EDP", y=2024, fam="Amber Spicy",
      style="spicy sweet", lon="long", proj="moderate",
      prof="Creed Centaurus-inspired: cinnamon/pink pepper/cardamom over patchouli with tonka-vanilla-benzoin.",
      acc=["warm spicy","sweet","amber","powdery"],
      top=["cinnamon","pink pepper","cardamom"], heart=["patchouli"], base=["tonka bean","vanilla","benzoin"]),
 dict(name="Black", g="men", c="EDP", y=None, fam="Unverified (identity not confirmed)",
      style="unconfirmed", lon=None, proj=None,
      prof="No 'Rayhaan Black' found in reviewed sources. Identity/scent data need manual confirmation.", nr=1),
 dict(name="Ruby", g="unisex", c="EDP", y=None, fam="Unverified (identity not confirmed)",
      style="unconfirmed", lon=None, proj=None,
      prof="No 'Rayhaan Ruby' found in reviewed sources. Identity/scent data need manual confirmation.", nr=1),
 dict(name="Sapphire", g="unisex", c="EDP", y=None, fam="Unverified (identity not confirmed)",
      style="unconfirmed", lon=None, proj=None,
      prof="No 'Rayhaan Sapphire' found (note: Rasasi released a 'Hawas Sapphire' 2026). Identity needs manual confirmation.", nr=1),
 dict(name="Topaze", g="unisex", c="EDP", y=None, fam="Unverified (identity not confirmed)",
      style="unconfirmed", lon=None, proj=None,
      prof="No 'Rayhaan Topaze' found in reviewed sources. Identity/scent data need manual confirmation.", nr=1),
 dict(name="Noor", g="unisex", c="EDP", y=None, fam="Unverified (identity not confirmed)",
      style="unconfirmed", lon=None, proj=None,
      prof="No 'Rayhaan Noor' found in reviewed sources (name overlaps Arabiyat 'Al Noor'). Identity needs manual confirmation.", nr=1),
]

# ---------------------------------------------------------------------------
# RASASI (28)
# ---------------------------------------------------------------------------
RASASI = [
 dict(name="Hawas for Him", g="men", c="EDP", y=2015, fam="Aromatic Aquatic",
      style="fresh fruity marine crowd-pleaser", lon="long", proj="strong",
      prof="Paco Rabanne Invictus-profile aquatic-fruity with ambergris warmth. NOTE: often mislabelled an Aventus clone — it is not; different family.",
      acc=["aquatic","fruity","citrus","marine","musky"],
      top=["bergamot","lemon","apple","cinnamon"], heart=["plum","orange blossom","cardamom"],
      base=["ambergris","musk","driftwood","patchouli"]),
 dict(name="Hawas Ice", g="men", c="EDP", y=2023, fam="Aromatic Aquatic",
      style="sweet fresh fruity", lon="long", proj="strong",
      prof="Sweeter, green-apple/bubblegum Invictus Aqua-style take on Hawas.",
      acc=["aquatic","fruity","sweet","citrus","musky"],
      top=["apple","lemon","bergamot","star anise"], heart=["plum","orange blossom","cardamom"],
      base=["musk","amber","driftwood","moss"]),
 dict(name="Hawas Black", g="men", c="EDP", y=2024, fam="Fruity Chypre",
      style="fruity woody smoky", lon="long", proj="strong",
      prof="Nishane Hacivat-style: fresh fruity opening over a smooth woody-amber base.",
      acc=["fruity","woody","smoky","chypre","fresh"],
      top=["pineapple","bergamot","grapefruit"], heart=["jasmine","patchouli"], base=["oakmoss","cedar","musk"]),
 dict(name="Hawas Fire", g="unisex", c="EDP", y=2025, fam="Aromatic Fruity",
      style="fruity aquatic floral", lon="long", proj="strong",
      prof="Reviewed as a Gissah Imperial Valley take: clary sage + fruity jam into a marine-white-floral heart.",
      acc=["fruity","aromatic","aquatic","sweet","floral"],
      top=["clary sage","fruity notes"], heart=["marine notes","white florals"], base=["musk","amber"], nr=1),
 dict(name="Hawas Elixir", g="unisex", c="EDP", y=2024, fam="Aromatic Aquatic",
      style="richer Hawas", lon="long", proj="strong",
      prof="A deeper, more concentrated Hawas; no distinct external designer target established.",
      acc=["aquatic","fruity","sweet","amber","musky"],
      top=["bergamot","apple"], heart=["plum","cardamom"], base=["ambergris","musk","amber"], nr=1),
 dict(name="Hawas Tropical", g="men", c="EDP", y=2025, fam="Aromatic Green",
      style="coconut fig tropical", lon="very long", proj="strong",
      prof="Coconut-water/fig-leaf/ginger tropical; reviewers compare to 'Paradise Garden' (target house unconfirmed).",
      acc=["coconut","green","fresh","fruity","woody"],
      top=["coconut water","fig leaf","ginger"], heart=["coconut","fig","mint"],
      base=["sandalwood","tonka bean","musk"], nr=1),
 dict(name="Hawas Eclat", g="women", c="EDP", y=2025, fam="Floral Fruity",
      style="lychee-rose feminine", lon="long", proj="moderate",
      prof="Hawas For Her Éclat: PdM Delina / Delina Exclusif-style lychee-rose with pear and pistachio.",
      acc=["floral","fruity","rose","sweet","lychee"],
      top=["litchi","pear","bergamot","pistachio"], heart=["rose","incense"],
      base=["vanilla","musk","amber","woods"]),
 dict(name="Hawas Viper", g="men", c="EDP", y=2025, fam="Aromatic Fruity Tobacco",
      style="smoky tobacco fruity", lon="long", proj="strong",
      prof="Smoky tobacco-coffee-raspberry; reviewers cite the niche 'Terroni' (OP) — target house unconfirmed.",
      acc=["tobacco","warm spicy","fruity","smoky","aromatic"],
      top=["saffron","cannabis accord","thyme","davana"], heart=["tobacco","coffee","cinnamon","raspberry"],
      base=["gurjan balsam","musk","tonka bean"], nr=1),
 dict(name="Hawas Atlantis", g="unisex", c="EDP", y=2025, fam="Aromatic Aquatic",
      style="green aquatic", lon="long", proj="strong",
      prof="Greener aquatic reviewed as an Invictus Parfum-adjacent take.",
      acc=["aquatic","green","fresh","marine","musky"],
      top=["marine notes","bergamot"], heart=["green notes"], base=["ambergris","musk","woods"], nr=1),
 dict(name="Hawas Pink", g="women", c="EDP", y=2025, fam="Amber Gourmand",
      style="sweet gourmand", lon="long", proj="moderate",
      prof="Cotton-candy/marshmallow gourmand; no clear external target — original-leaning.",
      acc=["sweet","gourmand","vanilla","floral","powdery"],
      top=["cinnamon","nutmeg","neroli"], heart=["marshmallow","tuberose","orange blossom"],
      base=["cotton candy","vanilla","tonka bean"], nr=1),
 dict(name="Hawas Thunder", g="men", c="EDP", y=2026, fam="Spicy Citrus Woody",
      style="spicy fresh woody", lon="long", proj="strong",
      prof="Bergamot/ginger/apple spicy-woody reviewers say recalls YSL MYSLF L'Absolu.",
      acc=["citrus","warm spicy","woody","fresh","amber"],
      top=["bergamot","ginger","apple"], heart=["spicy notes"], base=["woods","amber"], nr=1),
 dict(name="Hawas Exotic", g="men", c="EDP", y=2026, fam="Amber Woody",
      style="coconut spicy woody", lon="long", proj="strong",
      prof="Coconut/bergamot with lavender-cardamom over amber-woods-spice; no firm external target.",
      acc=["coconut","woody","warm spicy","amber","aromatic"],
      top=["bergamot","coconut"], heart=["lavender","cardamom"], base=["amber","woods","spices"], nr=1),
 dict(name="Hawas Lava Gold", g="men", c="EDP", y=2026, fam="Amber Woody",
      style="fruity leather oud", lon="long", proj="strong",
      prof="Juicy citrus-fruit opening over smoky leather/oud/saffron/raspberry and a caramel-amber base; no single external target established.",
      acc=["fruity","leather","oud","woody","amber"],
      top=["pineapple","grapefruit","apple","lemon"], heart=["leather","saffron","oud","raspberry"],
      base=["patchouli","amber","moss","caramel"], nr=1),
 dict(name="Hawas Glitz", g="unisex", c="EDP", y=2026, fam="Amber Vanilla",
      style="fruity powdery vanilla", lon="long", proj="moderate",
      prof="Fruity-floral vanilla-caramel gourmand; no firm external target.",
      acc=["sweet","vanilla","fruity","powdery","floral"],
      top=["bergamot","nut","pear"], heart=["orange blossom","orris","rose","geranium"],
      base=["caramel","musk","sandalwood","vanilla"], nr=1),
 dict(name="Hawas Highness", g="men", c="EDP", y=2026, fam="Floral Woody",
      style="spicy floral woody", lon="long", proj="strong",
      prof="Citrus-spice-amber over jasmine/violet/rose and cedar-vetiver-patchouli; reviewed as a clone but no named target surfaced.",
      acc=["floral","woody","warm spicy","citrus","amber"],
      top=["citrus","spicy notes","amber"], heart=["jasmine","violet","rose"],
      base=["cedar","vetiver","patchouli"], nr=1),
 dict(name="Hawas Overdose", g="men", c="EDP", y=2026, fam="Amber Gourmand",
      style="sweet spicy gourmand", lon="long", proj="strong",
      prof="Praline/chocolate/vanilla gourmand reviewers place in the Parfums de Marly Althair lane.",
      acc=["sweet","gourmand","amber","chocolate","warm spicy"],
      top=["spicy notes","aromatic notes"], heart=["orange blossom","amber","guaiac wood"],
      base=["vanilla","praline","chocolate","ambergris"], nr=1),
 dict(name="Hawas Chrome", g="unisex", c="EDP", y=2026, fam="Fruity",
      style="juicy fruity", lon="long", proj="strong",
      prof="Xerjoff Erba Pura-style juicy yellow-fruits and tropical fruit over amber-vanilla-musk.",
      acc=["fruity","sweet","citrus","amber","vanilla"],
      top=["yellow fruits","peach","orange"], heart=["water fruits","mango","passion fruit"],
      base=["amber","vanilla","musk"], nr=1),
 dict(name="Hawas Rouge", g="unisex", c="EDP", y=None, fam="Unverified (data pending)",
      style="unconfirmed", lon=None, proj=None,
      prof="Part of the Hawas line per retailers but no notes/inspiration found in reviewed sources. Awaiting scent data.", nr=1),
 dict(name="Hawas Addiction", g="unisex", c="EDP", y=2026, fam="Amber Gourmand",
      style="creamy dessert gourmand", lon="long", proj="moderate",
      prof="Vanilla/caramel/ice-cream/coconut-milk dessert gourmand; no firm external target.",
      acc=["sweet","gourmand","vanilla","coconut","creamy"],
      top=["vanilla","caramel","cotton candy","marshmallow","ice cream accord"],
      heart=["coconut milk","vanilla","milk"], base=["amber","cedar","moss"], nr=1),
 dict(name="La Yuqawam Homme", g="men", c="EDP", y=2012, fam="Leather",
      style="smoky raspberry leather", lon="very long", proj="strong",
      prof="Tom Ford Tuscan Leather-style: raspberry/saffron/thyme over incense-jasmine with a suede-leather base (also compared to LNDH).",
      acc=["leather","fruity","smoky","suede","woody"],
      top=["raspberry","saffron","thyme"], heart=["olibanum","jasmine","artemisia"],
      base=["leather","suede","woods","amber"]),
 dict(name="La Yuqawam Ambergris Showers", g="men", c="EDP", y=2016, fam="Leather",
      style="green leather mate", lon="long", proj="strong",
      prof="Effectively a 1:1 Memo Irish Leather clone (leather, juniper, mate) — despite the name it contains no ambergris accord focus.",
      acc=["leather","green","aromatic","woody"],
      top=["violet leaves","tangerine","galbanum"], heart=["mate","clary sage"],
      base=["leather","vetiver","styrax"]),
 dict(name="La Yuqawam Tobacco Blaze", g="men", c="EDP", y=2013, fam="Leather Oud",
      style="leather oud", lon="very long", proj="strong",
      prof="Reviewed as 'La Yuqawam Homme without the raspberry' — a leathery-oud Tuscan Leather relative.",
      acc=["leather","oud","warm spicy","woody","amber"],
      top=["saffron","neroli","lily-of-the-valley"], heart=["apricot","violet","coumarin","amber","cedar"],
      base=["leather","oud","patchouli"], nr=1),
 dict(name="Shuhrah Pour Homme", g="men", c="EDP", y=2015, fam="Woody Aromatic",
      style="green rosy woody", lon="long", proj="moderate",
      prof="Distinctive tomato-leaf/rose/freesia woody with a leather-oud base; sits near the Silver Mountain Water cluster but is largely its own thing.",
      acc=["green","woody","rose","aromatic","leather"],
      top=["tomato leaf","rose","freesia"], heart=["rose","sandalwood","cedar","jasmine"],
      base=["leather","oud","musk","oakmoss","amber"], nr=1),
 dict(name="Daarej Pour Homme", g="men", c="EDP", y=2011, fam="Amber Spicy",
      style="spicy powdery", lon="long", proj="moderate",
      prof="Valentino V pour Homme-style: cumin/cardamom/artemisia over rose-orris with a vanilla-tonka-amber base.",
      acc=["warm spicy","powdery","sweet","amber","woody"],
      top=["cumin","cardamom","artemisia"], heart=["rose","orris root"],
      base=["vanilla","tonka bean","amber","sandalwood","patchouli","musk"]),
 dict(name="Fattan Pour Homme", g="men", c="EDP", y=2018, fam="Woody Citrus",
      style="fresh vetiver citrus", lon="long", proj="moderate",
      prof="Hermès Terre d'Hermès-inspired grapefruit/pepper over vetiver-cedar-patchouli with oakmoss-benzoin-amber; built differently but shares the DNA.",
      acc=["citrus","woody","aromatic","fresh","earthy"],
      top=["grapefruit","bergamot","pink pepper"], heart=["vetiver","cedar","patchouli","lily-of-the-valley"],
      base=["oakmoss","benzoin","amber"]),
 dict(name="Al Wisam Day", g="men", c="EDP", y=2009, fam="Woody Aromatic",
      style="fresh rosy green woody", lon="long", proj="moderate",
      prof="Rosier Creed Silver Mountain Water-style: bergamot/geranium/lavender over rose-sandalwood-clary sage with a musk-oakmoss-oud base.",
      acc=["fresh","green","woody","rose","aromatic"],
      top=["bergamot","geranium","lavender"], heart=["rose","sandalwood","clary sage","cedar"],
      base=["musk","oakmoss","oud","amber"]),
 dict(name="Al Wisam Evening", g="men", c="EDP", y=2009, fam="Woody Aromatic",
      style="green woody", lon="long", proj="moderate",
      prof="A distinct green-woody companion to Al Wisam Day; no clear external designer target — original-leaning.",
      acc=["green","woody","aromatic","fresh"],
      top=["lavender","lemon"], heart=["galbanum","black currant leaf","rose"], base=["sandalwood","musk"], nr=1),
 dict(name="Yanis 12:01 AM", g="unisex", c="EDP", y=None, fam="Unverified (data pending)",
      style="unconfirmed", lon=None, proj=None,
      prof="Listed in target catalogue but not found in reviewed sources with a note pyramid or inspiration. Awaiting scent data.", nr=1),
]

# ---------------------------------------------------------------------------
# NEW REFERENCE TARGETS for Batch 2 (existing ones reused from Batch 1)
# ---------------------------------------------------------------------------
REFS2 = [
 dict(brand="Jean Paul Gaultier", name="Le Male Elixir", fam="Amber Gourmand",
      acc=["sweet","vanilla","tobacco","honey","amber"],
      top=["lavender","mint"], heart=["honey","cinnamon"], base=["vanilla","tonka bean","benzoin"]),
 dict(brand="Simone Andreoli", name="Wavechild", fam="Fruity Aquatic",
      acc=["fruity","sweet","aquatic","marine","coconut"],
      top=["melon","blood orange"], heart=["watermelon","coconut"], base=["marine notes","amberwood","cacao"]),
 dict(brand="Dior", name="Homme Cologne", fam="Citrus Musky",
      acc=["citrus","fresh","clean","musky","woody"],
      top=["bergamot","grapefruit"], heart=["neroli"], base=["white musk","woods"]),
 dict(brand="Nishane", name="Halfeti", fam="Amber Spicy",
      acc=["warm spicy","incense","amber","creamy","woody"],
      top=["nutmeg","clove","saffron"], heart=["rose","jasmine","tobacco"], base=["oud","amber","leather","tonka bean"]),
 dict(brand="Emporio Armani", name="Stronger With You Leather", fam="Woody Leather",
      acc=["leather","woody","sweet","warm spicy"],
      top=["chestnut","spices"], heart=["sage"], base=["vanilla","leather","suede"]),
 dict(brand="Creed", name="Centaurus", fam="Amber Spicy",
      acc=["warm spicy","sweet","amber","powdery","woody"],
      top=["cinnamon","pink pepper","cardamom"], heart=["patchouli","orris"], base=["tonka bean","vanilla","benzoin"]),
 dict(brand="Paco Rabanne", name="Invictus", fam="Aromatic Aquatic",
      acc=["aquatic","fresh","marine","woody","fruity"],
      top=["grapefruit","marine notes","mandarin"], heart=["bay leaf","jasmine"], base=["ambergris","guaiac wood","patchouli","oakmoss"]),
 dict(brand="Paco Rabanne", name="Invictus Aqua", fam="Aromatic Aquatic",
      acc=["aquatic","fresh","citrus","marine","woody"],
      top=["grapefruit","bergamot","marine notes"], heart=["bay leaf"], base=["ambergris","cedar","patchouli"]),
 dict(brand="Paco Rabanne", name="Invictus Parfum", fam="Aromatic Woody",
      acc=["woody","aromatic","green","amber","fresh"],
      top=["thyme","bergamot"], heart=["cypress","tonka bean"], base=["woods","ambergris"]),
 dict(brand="Gissah", name="Imperial Valley", fam="Aromatic Fruity",
      acc=["fruity","aromatic","aquatic","sweet","floral"],
      top=["clary sage","apple","fruity notes"], heart=["marine notes","white florals"], base=["musk","amber","woods"]),
 dict(brand="Parfums de Marly", name="Delina", fam="Floral Fruity",
      acc=["floral","fruity","rose","sweet","lychee"],
      top=["litchi","rhubarb","bergamot"], heart=["turkish rose","peony"], base=["vanilla","musk","cashmeran","incense"]),
 dict(brand="Xerjoff", name="Erba Pura", fam="Fruity",
      acc=["fruity","sweet","citrus","amber","vanilla"],
      top=["orange","lemon","bergamot"], heart=["fruity notes"], base=["amber","white musk","vanilla"]),
 dict(brand="Tom Ford", name="Tuscan Leather", fam="Leather",
      acc=["leather","fruity","smoky","suede","woody"],
      top=["raspberry","saffron","thyme"], heart=["olibanum","jasmine"], base=["leather","suede","amber","woods"]),
 dict(brand="Memo Paris", name="Irish Leather", fam="Leather",
      acc=["leather","green","aromatic","woody"],
      top=["juniper berries","violet leaves","cardamom"], heart=["mate","geranium"], base=["leather","woods","musk"]),
 dict(brand="Valentino", name="V pour Homme", fam="Amber Spicy",
      acc=["warm spicy","powdery","sweet","amber","woody"],
      top=["cinnamon","cardamom","bergamot"], heart=["rose","orris"], base=["vanilla","tonka bean","amber","sandalwood"]),
 dict(brand="Hermes", name="Terre d'Hermes", fam="Woody Citrus",
      acc=["citrus","woody","aromatic","earthy","fresh"],
      top=["grapefruit","orange"], heart=["pink pepper","pelargonium"], base=["vetiver","cedar","patchouli","benzoin"]),
 dict(brand="Yves Saint Laurent", name="MYSLF L'Absolu", fam="Amber Floral",
      acc=["floral","warm spicy","woody","amber","fresh"],
      top=["bergamot","ginger"], heart=["orange blossom"], base=["patchouli","woods","amber"]),
]

# ---------------------------------------------------------------------------
# BATCH-2 RELATIONSHIPS
# ---------------------------------------------------------------------------
R2 = []
def rel(frm,to,typ,ov,op,he,dr,pe,cc,reason,honest,evid,ver,nr,srcs):
    R2.append(dict(frm=frm,to=to,typ=typ,ov=ov,op=op,he=he,dr=dr,pe=pe,cc=cc,
        reason=reason,honest=honest,evid=evid,ver=ver,nr=nr,srcs=srcs,batch=2))

FR = "https://www.fragrantica.com/perfume/"

# ---- RAYHAAN ----
rel("Rayhaan|Elixir","Jean Paul Gaultier|Le Male Elixir","INSPIRED_BY",
    0.62,0.60,0.62,0.65,0.75,0.45,
    "Reviewed as indistinguishable-to-most from JPG Le Male Elixir's sweet vanilla-tobacco-lavender profile.",
    "Conflicting evidence: other roundups instead call it a Spicebomb interpretation. Confidence held low pending cross-check.",
    "Fragrantica reviews (Le Male Elixir) vs Fragrenza/PerfumesRoom/FridayCharm (Spicebomb) — sources disagree.",
    0,1,[FR+"Rayhaan/Rayhaan-Elixir-95265.html","https://theperfumesroom.com/top-10-rayhaan-perfumes-and-what-theyre-inspired-by/"])
rel("Rayhaan|Imperia","Creed|Aventus","INSPIRED_BY",
    0.68,0.70,0.66,0.64,0.70,0.60,
    "A close, affordable Creed Aventus interpretation: citrus/apple/mint over jasmine-rose-patchouli with oakmoss-amber-cedar.",
    "A step below top Aventus clones on refinement and smoke; more floral-woody than smoky-fruity.",
    "Parfumo + The Perfumes Room reviews naming Aventus as the reference.",
    0,0,[FR+"Rayhaan/Imperia-107858.html","https://www.parfumo.com/Perfumes/rayhaan/imperia"])
rel("Rayhaan|Pacific Aura","Louis Vuitton|Pacific Chill","VERIFIED_CLONE",
    0.86,0.88,0.84,0.80,0.70,0.80,
    "Widely reviewed as a near-1:1 Louis Vuitton Pacific Chill clone — 'identical after a few minutes' in multiple side-by-sides.",
    "LV holds ~4h vs ~3h here; some rank Azzurra Emerald Wade marginally closer.",
    "Fragrantica + multiple YouTube/TikTok side-by-side reviews ('strongest Pacific Chill clone').",
    1,0,[FR+"Rayhaan/Pacific-Aura-109709.html","https://www.youtube.com/watch?v=HHHdE_0r8wc"])
rel("Rayhaan|Pacific","Louis Vuitton|Pacific Chill","INSPIRED_BY",
    0.62,0.68,0.60,0.55,0.60,0.45,
    "Line-mate of Pacific Aura in the Pacific Chill citrus-aquatic lane.",
    "Fragrantica dates Pacific to 2022, before Pacific Chill (2023) — timeline inconsistency; treat as inspired/adjacent pending verification.",
    "Fragrantica + TikTok 'what is Rayhaan Pacific a clone of'.",
    0,1,[FR+"Rayhaan/Pacific-99293.html","https://www.tiktok.com/discover/what-is-rayhaan-pacific-a-clone-of"])
rel("Rayhaan|Pacific Aloha","Simone Andreoli|Wavechild","INSPIRED_BY",
    0.60,0.62,0.60,0.55,0.60,0.40,
    "Reviewed as the best current Wavechild dupe — melon/watermelon/coconut summer sweetness.",
    "Single-strand sourcing; niche target with limited corroboration.",
    "Retailer + Fragrantica descriptions naming Wavechild.",
    0,1,[FR+"Rayhaan/Pacific-Aloha-135601.html"])
rel("Rayhaan|Azul","Dior|Homme Cologne","INSPIRED_BY",
    0.55,0.60,0.52,0.50,0.55,0.35,
    "Clean lemon-bergamot citrus reviewers loosely compare to Dior Homme Cologne.",
    "Reviews vary on closeness; comparison is soft, not a confirmed dupe.",
    "Fragrantica user reviews.",
    0,1,[FR+"Rayhaan/Azul-135602.html"])
rel("Rayhaan|Ocean Rush","Rayhaan|Ocean Rush","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "Aromatic-aquatic with no consensus designer target; one reviewer likens the fleeting opening to Afnan 9AM Dive.",
    "No stable clone claim; closest DNA exposed instead.",
    "Fragrantica reviews.",
    0,1,[FR+"Rayhaan/Ocean-Rush-107857.html"])
rel("Rayhaan|Lion","Jean Paul Gaultier|Ultra Male","INSPIRED_BY",
    0.68,0.72,0.66,0.66,0.72,0.55,
    "Ultra Male-style sweet-spicy: lavender/pear/mint over cinnamon-cumin and vanilla-amber.",
    "Cumin adds a skankier facet not in Ultra Male; a variation rather than a 1:1 clone.",
    "Fragrantica + TikTok/YouTube 'Rayhaan Lion clone of' reviews.",
    0,0,[FR+"Rayhaan/Lion-105031.html","https://www.youtube.com/watch?v=7fdUASQxDIQ"])
rel("Rayhaan|Tiger","Nishane|Halfeti","INSPIRED_BY",
    0.68,0.68,0.68,0.68,0.70,0.55,
    "Halfeti-style spicy-milky-incense: nutmeg/clove over milk-rose with amber, patchouli, frankincense, labdanum.",
    "A more affordable, slightly simpler Halfeti reading.",
    "Fragrantica + fragranceknowledge review naming Halfeti.",
    0,0,[FR+"Rayhaan/Tiger-112886.html","https://www.tiktok.com/@fragranceknowledge/video/7456068369683369258"])
rel("Rayhaan|Corium","Emporio Armani|Stronger With You Leather","VERIFIED_CLONE",
    0.85,0.85,0.84,0.86,0.72,0.75,
    "Reviewed at ~95% of Emporio Armani Stronger With You Leather — chestnut/spice over a vanilla-leather-oud base.",
    "Slightly more leather; performance a notch below the original (6-8h).",
    "Fragrantica + Parfumo + retailer/YouTube all tag Stronger With You Leather.",
    1,0,[FR+"Rayhaan/Corium-97118.html","https://www.parfumo.com/Perfumes/rayhaan/corium","https://rimalalmisk.com/products/rayhaan-corium"])
rel("Rayhaan|Crimson","Creed|Centaurus","INSPIRED_BY",
    0.66,0.66,0.66,0.66,0.68,0.55,
    "A well-executed Creed Centaurus interpretation — cinnamon/pink pepper/cardamom over tonka-vanilla-benzoin.",
    "Softer and a touch simpler than Centaurus; not aggressive.",
    "Fragrantica + Parfumo + decant listings naming Centaurus.",
    0,0,[FR+"Rayhaan/Crimson-112761.html","https://www.parfumo.com/Perfumes/rayhaan/crimson"])
for nm in ["Panther","Cobra","Black","Ruby","Sapphire","Topaze","Noor"]:
    rel(f"Rayhaan|{nm}", f"Rayhaan|{nm}", "ORIGINAL_DNA",
        None,None,None,None,None,0.10,
        f"'Rayhaan {nm}' was not found in Fragrantica/Parfumo or any reviewed source. Product identity itself is unconfirmed — placeholder pending manual verification.",
        "No scent data or inspiration available; do NOT surface in user-facing features until confirmed.",
        "Absent from Rayhaan designer listing during research (verified names include Lion, Tiger, Wolf, Obsidian, Terra, Italia, Aquatica, Pharaoh, Divine).",
        0,1,["https://www.fragrantica.com/designers/Rayhaan.html"])

# ---- RASASI ----
rel("Rasasi|Hawas for Him","Paco Rabanne|Invictus","INSPIRED_BY",
    0.75,0.76,0.72,0.72,0.85,0.70,
    "The reference budget alternative to the Paco Rabanne Invictus aquatic-fruity accord, with added ambergris for stronger longevity.",
    "NOT an Aventus clone (a common myth) — different family; also carries some Acqua di Gio Absolu freshness.",
    "Multiple guides (Qamare, Mahadi, Sense Perfume) confirm the Invictus/Invictus-Aqua lineage and debunk the Aventus label.",
    1,0,[FR+"Rasasi/Hawas-72821.html","https://qamareperfumes.com/blogs/qamare-blog/rasasi-hawas-vs-creed-aventus-the-300-dupe-truth","https://senseperfume.in/rasasi-hawas-clone/"])
rel("Rasasi|Hawas Ice","Paco Rabanne|Invictus Aqua","INSPIRED_BY",
    0.72,0.74,0.70,0.68,0.75,0.60,
    "A sweeter, green-apple/bubblegum Invictus Aqua-style flanker of Hawas.",
    "More candied than Invictus Aqua; reads younger/sweeter.",
    "Fragrantica + Parfumo reviews naming Invictus Aqua.",
    0,0,[FR+"Rasasi/Hawas-Ice-89050.html","https://www.parfumo.com/Perfumes/Rasasi/hawas-ice"])
rel("Rasasi|Hawas Ice","Rasasi|Hawas for Him","SIMILAR_DNA",
    0.72,0.75,0.70,0.68,0.80,0.65,
    "Same Hawas aquatic-fruity backbone with a sweeter, icier twist.",
    "Flanker relationship; Ice is candied where the original is more marine.",
    "Fragrantica line comparisons.",
    0,0,[FR+"Rasasi/Hawas-Ice-89050.html"])
rel("Rasasi|Hawas Black","Nishane|Hacivat","VERIFIED_CLONE",
    0.76,0.76,0.74,0.74,0.75,0.68,
    "Reviewed as a Nishane Hacivat dupe — fresh fruity opening over a smooth woody-amber base.",
    "A grounded, slightly cheaper-smelling Hacivat; less oakmoss lift.",
    "Fragrantica + YouTube 'Rasasi Hawas Black - Nishane Hacivat Dupe'.",
    1,0,[FR+"Rasasi/Hawas-Black-96817.html","https://www.youtube.com/watch?v=zo2ST82JoCI"])
rel("Rasasi|Hawas Fire","Gissah|Imperial Valley","INSPIRED_BY",
    0.60,0.62,0.60,0.55,0.70,0.45,
    "Reviewed as a Gissah Imperial Valley take — clary sage and fruity jam into a marine white-floral heart.",
    "Niche target with limited corroboration; single main source.",
    "Fragrantica reviews.",
    0,1,[FR+"Rasasi/Hawas-Fire-101665.html"])
rel("Rasasi|Hawas Eclat","Parfums de Marly|Delina","INSPIRED_BY",
    0.68,0.66,0.70,0.66,0.65,0.55,
    "Hawas For Her Éclat reads as a PdM Delina / Delina Exclusif lychee-rose interpretation.",
    "Pear is less dominant and the drydown sweeter than Delina Exclusif — not a 1:1.",
    "Parfumo + Fragrantica + retailer listings naming Delina.",
    0,0,[FR+"Rasasi/Hawas-For-Her-Eclat-112708.html","https://www.parfumo.com/Perfumes/Rasasi/hawas-eclat"])
rel("Rasasi|Hawas Atlantis","Paco Rabanne|Invictus Parfum","INSPIRED_BY",
    0.58,0.58,0.56,0.55,0.70,0.42,
    "A greener aquatic reviewed as an Invictus Parfum-adjacent take within the Hawas family.",
    "Comparisons vary; the green twist pulls it away from a clean dupe.",
    "Fragrantica reviews.",
    0,1,[FR+"Rasasi/Hawas-Atlantis-112309.html"])
rel("Rasasi|Hawas Thunder","Yves Saint Laurent|MYSLF L'Absolu","INSPIRED_BY",
    0.55,0.58,0.52,0.50,0.65,0.40,
    "Bergamot/ginger/apple spicy-woody reviewers say recalls YSL MYSLF L'Absolu.",
    "Soft comparison; base is thinner/woodier than MYSLF.",
    "Fragrantica + iFragrance reviews.",
    0,1,[FR+"Rasasi/Hawas-Thunder-130938.html","https://ifragranceofficial.com/perfumes/hawas-thunder-rasasi/"])
rel("Rasasi|Hawas Overdose","Parfums de Marly|Althair","INSPIRED_BY",
    0.60,0.58,0.62,0.62,0.70,0.45,
    "Praline/chocolate/vanilla gourmand reviewers place in the PdM Althair lane.",
    "Late-to-market Althair-type; corroboration still thin.",
    "Fragrantica reviews.",
    0,1,[FR+"Rasasi/Hawas-Overdose-134748.html"])
rel("Rasasi|Hawas Chrome","Xerjoff|Erba Pura","INSPIRED_BY",
    0.66,0.70,0.64,0.60,0.70,0.50,
    "Juicy yellow-fruit and tropical-fruit profile reviewed as a Xerjoff Erba Pura take.",
    "Newer release; single main source so far.",
    "Fragrantica + ScentAdvice/iFragrance naming Erba Pura.",
    0,1,[FR+"Rasasi/Hawas-Chrome-136922.html","https://scentadvice.com/hawas-chrome-2026-rasasi/"])
for nm,note in [("Hawas Elixir","richer Hawas, no distinct external target"),
                ("Hawas Tropical","reviewers cite 'Paradise Garden' — target house unconfirmed"),
                ("Hawas Viper","reviewers cite niche 'Terroni (OP)' — target house unconfirmed"),
                ("Hawas Pink","cotton-candy gourmand, no external target"),
                ("Hawas Exotic","coconut-spicy woody, no external target"),
                ("Hawas Lava Gold","fruity-leather-oud, no single external target"),
                ("Hawas Glitz","fruity vanilla gourmand, no external target"),
                ("Hawas Highness","reviewed as a clone but no named target surfaced"),
                ("Hawas Addiction","dessert gourmand, no external target"),
                ("Hawas Rouge","no notes/inspiration found in reviewed sources")]:
    rel(f"Rasasi|{nm}", f"Rasasi|{nm}", "ORIGINAL_DNA",
        None,None,None,None,None,0.25,
        f"No confirmed designer/niche inspiration: {note}. Stored as original DNA; scent DNA where available exposes closest profile.",
        "Inspiration unverified or target house unconfirmed — flagged for a later deepening pass.",
        "Fragrantica profile / retailer listings; no cross-validated clone target.",
        0,1,[FR+"Rasasi/"])
rel("Rasasi|La Yuqawam Homme","Tom Ford|Tuscan Leather","VERIFIED_CLONE",
    0.80,0.80,0.78,0.80,0.80,0.75,
    "Long-standing, widely-recommended Tom Ford Tuscan Leather alternative — raspberry/saffron/smoke over a suede-leather base.",
    "Emphasises smoke and raspberry a touch more than leather vs the original; also compared to LNDH by some.",
    "Fragrantica + Parfumo + Basenotes consensus as a strong Tuscan Leather dupe.",
    1,0,[FR+"Rasasi/La-Yuqawam-Homme-19668.html","https://www.parfumo.com/Perfumes/Rasasi/La_Yuqawam_pour_Homme","https://basenotes.com/fragrances/la-yuqawam-pour-homme-by-rasasi.26140514"])
rel("Rasasi|La Yuqawam Ambergris Showers","Memo Paris|Irish Leather","VERIFIED_CLONE",
    0.85,0.85,0.84,0.85,0.75,0.70,
    "Regarded as essentially a 1:1 Memo Irish Leather clone — leather, juniper and mate — despite the misleading name.",
    "Contains no real ambergris focus; name is marketing.",
    "Fragrantica + Parfumo + Basenotes threads calling it an Irish Leather clone.",
    1,0,[FR+"Rasasi/La-Yuqawam-Ambergris-Showers-44896.html","https://www.parfumo.com/Perfumes/Rasasi/La_Yuqawam_Ambergris_Showers"])
rel("Rasasi|La Yuqawam Tobacco Blaze","Rasasi|La Yuqawam Homme","SIMILAR_DNA",
    0.72,0.68,0.72,0.75,0.80,0.60,
    "Reviewed as 'La Yuqawam Homme without the raspberry' — same leathery-oud Tuscan Leather relative.",
    "Drops the raspberry brightness; darker and more oud-leather.",
    "Fragrantica + Parfumo comparisons within the La Yuqawam line.",
    0,0,[FR+"Rasasi/Tobacco-Blaze-21365.html","https://www.parfumo.com/Perfumes/Rasasi/La_Yuqawam_Tobacco_Blaze"])
rel("Rasasi|La Yuqawam Tobacco Blaze","Tom Ford|Tuscan Leather","INSPIRED_BY",
    0.62,0.58,0.62,0.66,0.78,0.50,
    "Shares the Tuscan Leather leather-suede DNA via the La Yuqawam base, minus the raspberry.",
    "Further from Tuscan Leather than the original La Yuqawam Homme.",
    "Derived from La Yuqawam line reviews.",
    0,1,[FR+"Rasasi/Tobacco-Blaze-21365.html"])
rel("Rasasi|Daarej Pour Homme","Valentino|V pour Homme","INSPIRED_BY",
    0.70,0.70,0.70,0.68,0.65,0.55,
    "A good Valentino V pour Homme alternative — cumin/cardamom over rose-orris with a vanilla-tonka-amber base.",
    "Cheaper materials; a touch more powdery-spicy.",
    "Fragrantica + Parfumo + YouTube naming V pour Homme.",
    0,0,[FR+"Rasasi/Daarej-pour-Homme-19688.html","https://www.parfumo.com/Perfumes/Rasasi/Daarej_pour_Homme"])
rel("Rasasi|Fattan Pour Homme","Hermes|Terre d'Hermes","INSPIRED_BY",
    0.66,0.68,0.64,0.62,0.65,0.55,
    "Terre d'Hermès-inspired grapefruit/pepper over vetiver-cedar-patchouli with an oakmoss-benzoin-amber base.",
    "Built differently — more oakmoss/benzoin; shares the DNA rather than cloning it.",
    "Fragrantica + Parfumo + Scent Buddy review noting the Terre d'Hermès inspiration.",
    0,0,[FR+"Rasasi/Fattan-53484.html","https://scentbuddy.blog/2026/03/15/rasasi-fattan-pour-homme-review/"])
rel("Rasasi|Al Wisam Day","Creed|Silver Mountain Water","INSPIRED_BY",
    0.68,0.66,0.68,0.66,0.65,0.58,
    "A rosier Creed Silver Mountain Water — bergamot/geranium/lavender over rose-sandalwood with a musk-oakmoss-oud base.",
    "Reaches SMW's inky freshness by a rosier route; not a straight copy.",
    "Fragrantica + Parfumo + retailer ('Creed SMW clone') listings.",
    0,0,[FR+"Rasasi/Al-Wisam-Day-19650.html","https://www.parfumo.com/Perfumes/Rasasi/al-wisam-day"])
rel("Rasasi|Al Wisam Evening","Rasasi|Al Wisam Evening","ORIGINAL_DNA",
    None,None,None,None,None,0.30,
    "A distinct green-woody companion to Al Wisam Day with no clear external designer target.",
    "Reviewers describe it as its own thing, unlike the SMW-leaning Day version.",
    "Fragrantica + Parfumo reviews.",
    0,1,[FR+"Rasasi/Al-Wisam-Evening-19649.html"])
rel("Rasasi|Shuhrah Pour Homme","Rasasi|Shuhrah Pour Homme","ORIGINAL_DNA",
    None,None,None,None,None,0.35,
    "Distinctive tomato-leaf/rose woody-leather with no consensus designer target; sits near the Silver Mountain Water cluster but is largely original.",
    "Green-sour rose facet is unusual; no reliable single clone target.",
    "Fragrantica + Basenotes reviews noting its uniqueness.",
    0,1,[FR+"Rasasi/Shuhrah-Pour-Homme-53578.html","https://basenotes.com/fragrances/shuhrah-pour-homme-by-rasasi.26158834"])
for nm in ["Yanis 12:01 AM"]:
    rel(f"Rasasi|{nm}", f"Rasasi|{nm}", "ORIGINAL_DNA",
        None,None,None,None,None,0.10,
        f"'Rasasi {nm}' not found with a note pyramid or inspiration in reviewed sources — placeholder pending scent data.",
        "No scent data available; do NOT surface in user-facing features until researched.",
        "Absent from indexed Rasasi profiles during research.",
        0,1,["https://www.fragrantica.com/designers/Rasasi.html"])

if __name__ == "__main__":
    rep = b1.build_kb(
        extra_target_groups=[("Rayhaan","AE",RAYHAAN,2), ("Rasasi","AE",RASASI,2)],
        extra_refs=REFS2,
        extra_rels=R2,
        batch_no=2,
        brands_covered=["Afnan","Lattafa","Rayhaan","Rasasi"],
        report_name="coverage_report_batch2.json",
    )
    print(json.dumps(rep, indent=2, ensure_ascii=False))
